[toolchain]
anchor_version = "0.30.1"

[programs.devnet]
noble_distributor = "Dist1111111111111111111111111111111111111"

[programs.mainnet]
noble_distributor = "Dist1111111111111111111111111111111111111"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
build = "anchor build"
test = "anchor test"
