/**
 * Deterministic mock fixtures for Mission Control.
 *
 * Each `getX()` function is the swap point: replace its body with a fetch to
 * the FastAPI gateway (e.g. `${API_BASE}/dashboard/revenue`) and the panels
 * keep working unchanged.
 */

import type {
  Agent,
  AgentMeshSummary,
  AuditEntry,
  CashPosition,
  ComplianceAlert,
  DashboardOverview,
  Deal,
  Invoice,
  Job,
  KillSwitch,
  KpiTile,
  Permit,
  PermitForecastBucket,
  PipelineStage,
  ProgramReport,
  RevenueRule,
  SalesIntelligence,
  SystemsRegistry,
  VoiceSessionSummary,
  VoiceTranscriptTurn,
} from './types';

const NOW_ISO = '2026-05-09T14:35:00Z';

const minus = (mins: number) => new Date(Date.parse(NOW_ISO) - mins * 60_000).toISOString();
const plus = (mins: number) => new Date(Date.parse(NOW_ISO) + mins * 60_000).toISOString();

// ---------------------------------------------------------------------------
// KPIs (Executive Command Panel top row)
// ---------------------------------------------------------------------------

export const getKpis = (): KpiTile[] => [
  {
    id: 'pipeline',
    label: 'Pipeline Value',
    value: '$18.4M',
    raw: 18_412_500,
    source: 'CRM',
    delta: 0.062,
    deltaLabel: 'vs 30d',
    trend: 'up',
    health: 'healthy',
    href: '/dashboard/revenue',
    deploymentStatus: 'LIVE',
  },
  {
    id: 'deposits',
    label: 'Deposits Collected (MTD)',
    value: '$1.27M',
    raw: 1_270_400,
    source: 'Stripe / QB',
    delta: 0.181,
    deltaLabel: 'vs forecast',
    trend: 'up',
    health: 'healthy',
    href: '/dashboard/revenue',
    deploymentStatus: 'STAGED',
  },
  {
    id: 'jobs',
    label: 'Active Jobs',
    value: '37',
    raw: 37,
    source: 'GCagent',
    delta: 3,
    deltaLabel: 'WoW',
    trend: 'up',
    health: 'healthy',
    href: '/dashboard/jobs',
    deploymentStatus: 'LIVE',
  },
  {
    id: 'permits',
    label: 'Permit Queue',
    value: '24',
    raw: 24,
    source: 'PermitStream',
    delta: -2,
    deltaLabel: 'WoW',
    trend: 'down',
    health: 'degraded',
    hint: '4 stalled in corrections > 14d',
    href: '/dashboard/permits',
    deploymentStatus: 'STAGED',
  },
  {
    id: 'gp',
    label: 'Gross Margin (Q2 forecast)',
    value: '21.4%',
    raw: 0.214,
    source: 'ERPNext',
    delta: -0.012,
    deltaLabel: 'vs target',
    trend: 'down',
    health: 'degraded',
    hint: '2 jobs under GP floor',
    href: '/dashboard/jobs',
    deploymentStatus: 'MODELED',
  },
  {
    id: 'agents',
    label: 'AI Agent Health',
    value: '108 / 112',
    raw: 108,
    source: 'Orchestrator',
    delta: -1,
    deltaLabel: '1h',
    trend: 'down',
    health: 'degraded',
    hint: '2 degraded · 2 unhealthy',
    href: '/dashboard/agents',
    deploymentStatus: 'MODELED',
  },
  {
    id: 'voice',
    label: 'Voice Latency (p95)',
    value: '312ms',
    raw: 312,
    source: 'Stephanie.ai / LiveKit',
    delta: 18,
    deltaLabel: '15m',
    trend: 'up',
    health: 'healthy',
    href: '/dashboard/voice',
    deploymentStatus: 'LIVE',
  },
  {
    id: 'compliance',
    label: 'Compliance Alerts',
    value: '3',
    raw: 3,
    source: 'Cyborg.ai',
    delta: 1,
    deltaLabel: '24h',
    trend: 'up',
    health: 'degraded',
    hint: '1 critical · 2 warnings',
    href: '/dashboard/compliance',
    deploymentStatus: 'MODELED',
  },
  {
    id: 'completion',
    label: 'Build Completion',
    value: '100%',
    raw: 1.0,
    source: 'Program',
    delta: 0.123,
    deltaLabel: 'vs last',
    trend: 'up',
    health: 'healthy',
    hint: '14 of 14 projects complete',
    href: '/dashboard/program',
    deploymentStatus: 'LIVE',
  },
];

// ---------------------------------------------------------------------------
// Cash, pipeline, deals, invoices  (Revenue Warboard)
// ---------------------------------------------------------------------------

export const getCashPosition = (): CashPosition => ({
  asOf: NOW_ISO,
  operating: 1_842_300,
  reserve: 750_000,
  escrow: 412_500,
  pendingDeposits: 318_000,
  pendingPayables: 624_900,
  runwayDays: 184,
});

export const getPipeline = (): PipelineStage[] => [
  { id: 'lead', name: 'Lead', count: 41, value: 8_140_000, staleCount: 6 },
  { id: 'proposal', name: 'Proposal', count: 22, value: 5_870_000, staleCount: 4 },
  { id: 'deposit', name: 'Deposit Pending', count: 9, value: 2_310_000, staleCount: 3 },
  { id: 'scheduled', name: 'Scheduled', count: 14, value: 4_220_000, staleCount: 1 },
  { id: 'production', name: 'In Production', count: 23, value: 11_240_000, staleCount: 0 },
  { id: 'invoice', name: 'Invoicing', count: 12, value: 3_980_000, staleCount: 2 },
  { id: 'cash', name: 'Cash Collected', count: 18, value: 5_460_000, staleCount: 0 },
];

export const getStaleDeals = (): Deal[] => [
  {
    id: 'd-2041',
    name: 'Highland Estate · Phase II',
    client: 'Highland Holdings LLC',
    stage: 'Proposal',
    value: 1_240_000,
    ageDays: 22,
    owner: 'M. Velasquez',
    nextAction: 'Confirm scope changes; resend signed proposal',
    blockers: ['Awaiting client architect sign-off'],
    depositRequired: true,
    depositCollected: false,
  },
  {
    id: 'd-2058',
    name: 'Newbury Coastal Renovation',
    client: 'B. Whitcomb',
    stage: 'Deposit Pending',
    value: 482_000,
    ageDays: 9,
    owner: 'A. Park',
    nextAction: 'Send deposit invoice; do NOT schedule until cleared',
    blockers: ['Deposit not collected — schedule blocked by policy'],
    depositRequired: true,
    depositCollected: false,
  },
  {
    id: 'd-2063',
    name: 'Tannery Mills Adaptive Reuse',
    client: 'Tannery Mills LP',
    stage: 'Proposal',
    value: 3_120_000,
    ageDays: 14,
    owner: 'M. Velasquez',
    nextAction: 'Re-price after MEP redline; schedule walkthrough',
    blockers: ['MEP scope undefined'],
    depositRequired: true,
    depositCollected: false,
  },
  {
    id: 'd-2071',
    name: 'Salisbury Beach Multi-family',
    client: 'Coastline Capital',
    stage: 'Lead',
    value: 6_800_000,
    ageDays: 31,
    owner: 'D. Iyer',
    nextAction: 'Reassign or cull — 31d untouched',
    blockers: ['No response from client in 21d'],
    depositRequired: false,
    depositCollected: false,
  },
];

export const getInvoices = (): Invoice[] => [
  {
    id: 'i-9012',
    number: 'INV-2026-0412',
    job: 'NP-204 Highland Phase I',
    client: 'Highland Holdings LLC',
    amount: 184_500,
    daysOverdue: 22,
    status: 'overdue',
  },
  {
    id: 'i-9015',
    number: 'INV-2026-0418',
    job: 'NP-211 Plum Island Reno',
    client: 'A. Carmichael',
    amount: 96_400,
    daysOverdue: 11,
    status: 'overdue',
  },
  {
    id: 'i-9019',
    number: 'INV-2026-0421',
    job: 'NP-198 Tannery Mills',
    client: 'Tannery Mills LP',
    amount: 412_900,
    daysOverdue: 4,
    status: 'partial',
  },
  {
    id: 'i-9024',
    number: 'INV-2026-0426',
    job: 'NP-220 Newburyport Civic',
    client: 'City of Newburyport',
    amount: 318_700,
    daysOverdue: 0,
    status: 'sent',
  },
];

export const getRevenueRules = (): RevenueRule[] => [
  { id: 'r-deposit', rule: 'No deposit → no schedule', status: 'enforced', violations: 0 },
  { id: 'r-invoice', rule: 'No invoice → no progress', status: 'enforced', violations: 0 },
  { id: 'r-audit', rule: 'No audit log → no state change', status: 'enforced', violations: 0 },
  {
    id: 'r-gpfloor',
    rule: 'Hard GP floor (18%) on all production jobs',
    status: 'warning',
    violations: 2,
  },
  {
    id: 'r-aging',
    rule: 'AR > 30 days flagged for collections agent',
    status: 'enforced',
    violations: 1,
  },
];

// ---------------------------------------------------------------------------
// Construction Ops
// ---------------------------------------------------------------------------

export const getJobs = (): Job[] => [
  {
    id: 'j-204',
    code: 'NP-204',
    name: 'Highland Estate · Phase I',
    client: 'Highland Holdings LLC',
    pm: 'M. Velasquez',
    phase: 'production',
    contractValue: 4_120_000,
    billedToDate: 2_840_000,
    costToDate: 2_310_000,
    gpForecast: 0.224,
    gpFloor: 0.18,
    scheduleVariance: -3,
    health: 'healthy',
    blockers: [],
    depositCollected: true,
    nextMilestone: 'Rough-in inspection',
    nextMilestoneAt: plus(60 * 28),
  },
  {
    id: 'j-198',
    code: 'NP-198',
    name: 'Tannery Mills · Adaptive Reuse',
    client: 'Tannery Mills LP',
    pm: 'D. Iyer',
    phase: 'production',
    contractValue: 7_840_000,
    billedToDate: 3_120_000,
    costToDate: 2_960_000,
    gpForecast: 0.171,
    gpFloor: 0.18,
    scheduleVariance: -8,
    health: 'degraded',
    blockers: ['Steel delay 9d', 'MEP RFI #214 awaiting answer'],
    depositCollected: true,
    nextMilestone: 'Steel topping-out',
    nextMilestoneAt: plus(60 * 96),
  },
  {
    id: 'j-211',
    code: 'NP-211',
    name: 'Plum Island Renovation',
    client: 'A. Carmichael',
    pm: 'A. Park',
    phase: 'production',
    contractValue: 1_240_000,
    billedToDate: 712_000,
    costToDate: 690_000,
    gpForecast: 0.146,
    gpFloor: 0.18,
    scheduleVariance: -12,
    health: 'unhealthy',
    blockers: ['GP forecast below 18% floor', 'Coastal AHJ permit corrections'],
    depositCollected: true,
    nextMilestone: 'Permit re-submit',
    nextMilestoneAt: plus(60 * 6),
  },
  {
    id: 'j-220',
    code: 'NP-220',
    name: 'Newburyport Civic Hall',
    client: 'City of Newburyport',
    pm: 'M. Velasquez',
    phase: 'mobilization',
    contractValue: 5_840_000,
    billedToDate: 412_000,
    costToDate: 380_000,
    gpForecast: 0.236,
    gpFloor: 0.2,
    scheduleVariance: 1,
    health: 'healthy',
    blockers: [],
    depositCollected: true,
    nextMilestone: 'Site mobilization complete',
    nextMilestoneAt: plus(60 * 18),
  },
  {
    id: 'j-225',
    code: 'NP-225',
    name: 'Salisbury Cottages',
    client: 'Coastline Capital',
    pm: 'A. Park',
    phase: 'permitting',
    contractValue: 2_140_000,
    billedToDate: 0,
    costToDate: 18_400,
    gpForecast: 0.218,
    gpFloor: 0.18,
    scheduleVariance: 0,
    health: 'healthy',
    blockers: [],
    depositCollected: true,
    nextMilestone: 'Foundation permit issuance',
    nextMilestoneAt: plus(60 * 220),
  },
];

// ---------------------------------------------------------------------------
// PermitStream
// ---------------------------------------------------------------------------

export const getPermits = (): Permit[] => [
  {
    id: 'p-7401',
    number: 'NWB-2026-3101',
    job: 'NP-220 Newburyport Civic',
    ahj: 'Newburyport, MA',
    type: 'Building · Commercial',
    status: 'review',
    submittedAt: minus(60 * 24 * 8),
    ageDays: 8,
    forecastIssueAt: plus(60 * 24 * 12),
    reviewer: 'J. Hollis',
    zoningFlags: [],
  },
  {
    id: 'p-7388',
    number: 'PLM-2026-2104',
    job: 'NP-211 Plum Island Reno',
    ahj: 'Newbury, MA (Plum Island overlay)',
    type: 'Building · Coastal AE',
    status: 'corrections',
    submittedAt: minus(60 * 24 * 21),
    ageDays: 21,
    forecastIssueAt: plus(60 * 24 * 9),
    reviewer: 'C. Lefevre',
    zoningFlags: ['Coastal AE-9 setback', 'Wetlands NOI required'],
  },
  {
    id: 'p-7402',
    number: 'TAN-2026-0890',
    job: 'NP-198 Tannery Mills',
    ahj: 'Newburyport, MA',
    type: 'Building · Adaptive Reuse',
    status: 'review',
    submittedAt: minus(60 * 24 * 5),
    ageDays: 5,
    forecastIssueAt: plus(60 * 24 * 16),
    reviewer: 'J. Hollis',
    zoningFlags: ['Historic district overlay'],
  },
  {
    id: 'p-7410',
    number: 'SAL-2026-0331',
    job: 'NP-225 Salisbury Cottages',
    ahj: 'Salisbury, MA',
    type: 'Building · Residential',
    status: 'intake',
    submittedAt: minus(60 * 24 * 1),
    ageDays: 1,
    forecastIssueAt: plus(60 * 24 * 28),
    zoningFlags: [],
  },
  {
    id: 'p-7359',
    number: 'NWB-2026-2812',
    job: 'NP-204 Highland Phase I',
    ahj: 'Newburyport, MA',
    type: 'Electrical',
    status: 'issued',
    submittedAt: minus(60 * 24 * 14),
    ageDays: 14,
    forecastIssueAt: minus(60 * 24 * 1),
    reviewer: 'R. Costa',
    zoningFlags: [],
  },
];

export const getPermitForecast = (): PermitForecastBucket[] => [
  { ahj: 'Newburyport, MA', medianDays: 11, p90Days: 24, open: 9, issuedThisMonth: 6 },
  { ahj: 'Newbury, MA', medianDays: 18, p90Days: 42, open: 4, issuedThisMonth: 1 },
  { ahj: 'Salisbury, MA', medianDays: 14, p90Days: 28, open: 5, issuedThisMonth: 3 },
  { ahj: 'Amesbury, MA', medianDays: 9, p90Days: 19, open: 3, issuedThisMonth: 4 },
  { ahj: 'Boston, MA', medianDays: 27, p90Days: 64, open: 3, issuedThisMonth: 2 },
];

// ---------------------------------------------------------------------------
// Agent mesh
// ---------------------------------------------------------------------------

export const getAgents = (): Agent[] => [
  {
    id: 'a-stephanie',
    name: 'Stephanie.ai',
    family: 'Stephanie',
    role: 'Executive voice / orchestration',
    health: 'healthy',
    queueDepth: 2,
    inFlight: 1,
    p95LatencyMs: 312,
    errorRate: 0.004,
    uptime30d: 0.9994,
    lastHeartbeat: minus(0),
    killSwitchArmed: false,
    currentTask: 'Live call · Highland follow-up',
  },
  {
    id: 'a-gcagent',
    name: 'GCagent.ai',
    family: 'GCagent',
    role: 'Construction operations supervisor',
    health: 'healthy',
    queueDepth: 14,
    inFlight: 3,
    p95LatencyMs: 980,
    errorRate: 0.011,
    uptime30d: 0.9982,
    lastHeartbeat: minus(0),
    killSwitchArmed: false,
    currentTask: 'NP-198 schedule recompute',
  },
  {
    id: 'a-permit',
    name: 'PermitStream.ai',
    family: 'PermitStream',
    role: 'Permit forecasting + AHJ workflows',
    health: 'degraded',
    queueDepth: 31,
    inFlight: 2,
    p95LatencyMs: 2210,
    errorRate: 0.034,
    uptime30d: 0.9941,
    lastHeartbeat: minus(1),
    killSwitchArmed: false,
    currentTask: 'Newbury Coastal AE redline scan',
  },
  {
    id: 'a-cyborg',
    name: 'Cyborg.ai',
    family: 'Cyborg',
    role: 'Compliance / governance enforcement',
    health: 'healthy',
    queueDepth: 0,
    inFlight: 0,
    p95LatencyMs: 142,
    errorRate: 0.0,
    uptime30d: 1.0,
    lastHeartbeat: minus(0),
    killSwitchArmed: true,
  },
  {
    id: 'a-deepagent',
    name: 'DeepAgent',
    family: 'DeepAgent',
    role: 'Long-horizon research / proposals',
    health: 'healthy',
    queueDepth: 4,
    inFlight: 1,
    p95LatencyMs: 4810,
    errorRate: 0.018,
    uptime30d: 0.997,
    lastHeartbeat: minus(0),
    killSwitchArmed: false,
    currentTask: 'Tannery Mills MEP redline',
  },
  {
    id: 'a-kuzo',
    name: 'KUZO',
    family: 'KUZO',
    role: 'Field telemetry + sensor fusion',
    health: 'unhealthy',
    queueDepth: 0,
    inFlight: 0,
    p95LatencyMs: 0,
    errorRate: 0.0,
    uptime30d: 0.962,
    lastHeartbeat: minus(11),
    killSwitchArmed: false,
    currentTask: undefined,
  },
  {
    id: 'a-collector',
    name: 'AR-Collector',
    family: 'Other',
    role: 'AR > 30d outreach',
    health: 'healthy',
    queueDepth: 6,
    inFlight: 1,
    p95LatencyMs: 720,
    errorRate: 0.009,
    uptime30d: 0.9991,
    lastHeartbeat: minus(0),
    killSwitchArmed: false,
    currentTask: 'INV-2026-0412 follow-up',
  },
  {
    id: 'a-bidops',
    name: 'BidOps',
    family: 'Other',
    role: 'Subcontractor bid leveling',
    health: 'unhealthy',
    queueDepth: 0,
    inFlight: 0,
    p95LatencyMs: 0,
    errorRate: 1.0,
    uptime30d: 0.94,
    lastHeartbeat: minus(34),
    killSwitchArmed: false,
  },
];

export const getAgentSummary = (): AgentMeshSummary => {
  const agents = getAgents();
  const total = 112;
  const healthy = agents.filter((a) => a.health === 'healthy').length + (total - agents.length);
  const degraded = agents.filter((a) => a.health === 'degraded').length;
  const unhealthy = agents.filter((a) => a.health === 'unhealthy').length;
  const totalQueue = agents.reduce((s, a) => s + a.queueDepth, 0);
  const totalInFlight = agents.reduce((s, a) => s + a.inFlight, 0);
  const topLatencyMs = agents.reduce((m, a) => Math.max(m, a.p95LatencyMs), 0);
  return { total, healthy, degraded, unhealthy, totalQueue, totalInFlight, topLatencyMs };
};

// ---------------------------------------------------------------------------
// Compliance / Cyborg.ai
// ---------------------------------------------------------------------------

export const getComplianceAlerts = (): ComplianceAlert[] => [
  {
    id: 'c-501',
    ts: minus(48),
    severity: 'critical',
    category: 'erc1400',
    subject: 'Restricted transfer attempt',
    detail:
      'ERC-1400 restriction blocked transfer of NP-RE-204 from 0x4a…91 to non-whitelisted 0xb7…2c',
    agent: 'Cyborg.ai',
    resolved: false,
  },
  {
    id: 'c-502',
    ts: minus(220),
    severity: 'warn',
    category: 'sanctions',
    subject: 'OFAC list refresh',
    detail: 'Daily sanctions diff applied · 14 new entries · 0 portfolio matches',
    agent: 'Cyborg.ai',
    resolved: true,
  },
  {
    id: 'c-503',
    ts: minus(640),
    severity: 'warn',
    category: 'policy',
    subject: 'GP floor breach forecast',
    detail: 'Job NP-211 Plum Island forecast GP 14.6% below 18% floor — escalated to PM',
    agent: 'GCagent.ai',
    resolved: false,
  },
  {
    id: 'c-504',
    ts: minus(900),
    severity: 'info',
    category: 'signature',
    subject: 'HumanApprovalGateway',
    detail: 'Multi-sig 2/3 collected for NP-220 GMP amendment',
    agent: 'Cyborg.ai',
    resolved: true,
  },
  {
    id: 'c-505',
    ts: minus(1300),
    severity: 'critical',
    category: 'kill-switch',
    subject: 'Kill-switch armed: tx-broadcast',
    detail: 'Operator armed kill-switch on tx-broadcast scope after RPC anomaly',
    agent: 'Operator · m.velasquez',
    resolved: false,
  },
];

export const getKillSwitches = (): KillSwitch[] => [
  {
    id: 'k-tx',
    scope: 'tx-broadcast',
    armed: true,
    lastTriggeredAt: minus(1300),
    controller: 'm.velasquez (2/3 multi-sig)',
    description: 'Halts all on-chain broadcasts (Arbitrum + L1 anchors)',
  },
  {
    id: 'k-voice',
    scope: 'stephanie-outbound',
    armed: false,
    controller: 'm.velasquez (1/1)',
    description: 'Disables Stephanie outbound voice initiation',
  },
  {
    id: 'k-agents',
    scope: 'agent-mesh-write',
    armed: false,
    controller: 'm.velasquez (2/3 multi-sig)',
    description: 'Forces all agents into read-only mode',
  },
  {
    id: 'k-funds',
    scope: 'treasury-disbursement',
    armed: false,
    controller: 'DAO 4/7',
    description: 'Halts Stripe + bank disbursement workflows',
  },
];

// ---------------------------------------------------------------------------
// Audit chain
// ---------------------------------------------------------------------------

const HASHES = [
  '0x9a4f1c0b8e2c6d3f17a8b25c91d4f0e6a3b8c5d7e2f1a9b4c8d5e7f0a3b6c9d2',
  '0x7c1e9b3d5a8f2c0e4b7d1a9f6c3e8b5d2f0a7c4e9b1d6f3a0c5e8b2d7f4a1c9e',
  '0x4d8a2c6e1f5b9d3a7c0e8b4f2d6a9c5e1b3f7d0a8c2e5f9b4d7a1c6e3f0b5d8a',
  '0x1f5b8c3e9a2d7f4b0c6e1a8d3f9b5c2e7a4d0f6b8c3e1a9d5f2b7c0e4a8d6f3b',
  '0xb3e7a1d5f9c2b8d4a0e6c1f5b9d3a7c4e0f8b2d6a1c5e9b3f7d0a4c8e2b6f1d5',
  '0x6c2e9b5d1f7a3c8e4b0d6f2a9c5e1b7d3f0a8c4e9b2d6f1a5c0e7b3d8f4a2c6e',
  '0x2a8d4f0b6c1e9a5d3f7b0c4e8a2d6f1b9c5e3a7d4f0b8c2e6a1d5f9b3c7e4a0d',
];

export const getAudit = (): AuditEntry[] => [
  {
    id: 'au-9911',
    ts: minus(2),
    operator: 'm.velasquez',
    agent: 'GCagent.ai',
    action: 'job.schedule.update',
    subject: 'NP-198 · push topping-out 4d',
    approval: 'human',
    hash: HASHES[0],
    prevHash: HASHES[1],
    anchor: 'arbitrum:0x9a…c9d2 / block 184729031',
    status: 'committed',
  },
  {
    id: 'au-9910',
    ts: minus(8),
    operator: 'system',
    agent: 'Cyborg.ai',
    action: 'erc1400.transfer.block',
    subject: 'NP-RE-204 · 0x4a91 → 0xb72c (non-whitelisted)',
    approval: 'auto',
    hash: HASHES[1],
    prevHash: HASHES[2],
    status: 'committed',
  },
  {
    id: 'au-9909',
    ts: minus(14),
    operator: 'a.park',
    agent: 'PermitStream.ai',
    action: 'permit.submit',
    subject: 'PLM-2026-2104 · Plum Island corrections re-submit',
    approval: 'human',
    hash: HASHES[2],
    prevHash: HASHES[3],
    status: 'committed',
  },
  {
    id: 'au-9908',
    ts: minus(22),
    operator: 'm.velasquez',
    action: 'kill-switch.arm',
    subject: 'tx-broadcast',
    approval: 'multi-sig',
    hash: HASHES[3],
    prevHash: HASHES[4],
    anchor: 'arbitrum:0x1f…5d8a / block 184728994',
    status: 'committed',
  },
  {
    id: 'au-9907',
    ts: minus(45),
    operator: 'd.iyer',
    agent: 'GCagent.ai',
    action: 'invoice.send',
    subject: 'INV-2026-0421 · Tannery Mills · $412,900',
    approval: 'human',
    hash: HASHES[4],
    prevHash: HASHES[5],
    status: 'committed',
  },
  {
    id: 'au-9906',
    ts: minus(78),
    operator: 'system',
    agent: 'AR-Collector',
    action: 'invoice.followup',
    subject: 'INV-2026-0412 · 22d overdue · email + voice',
    approval: 'auto',
    hash: HASHES[5],
    prevHash: HASHES[6],
    status: 'committed',
  },
  {
    id: 'au-9905',
    ts: minus(120),
    operator: 'm.velasquez',
    action: 'gmp.amendment.sign',
    subject: 'NP-220 · GMP amendment #2',
    approval: 'multi-sig',
    hash: HASHES[6],
    prevHash: HASHES[0],
    anchor: 'arbitrum:0xb3…f1d5 / block 184728812',
    status: 'committed',
  },
];

// ---------------------------------------------------------------------------
// Voice console
// ---------------------------------------------------------------------------

export const getVoiceSession = (): VoiceSessionSummary => ({
  active: true,
  sessionId: 'lk-sess-9b1c4e7a',
  participants: 2,
  latencyMs: 312,
  packetLossPct: 0.4,
  asrModel: 'nova-3',
  ttsVoice: 'stephanie-v3',
  startedAt: minus(7),
  routedTo: ['GCagent.ai', 'AR-Collector'],
});

export const getVoiceTranscript = (): VoiceTranscriptTurn[] => [
  {
    id: 't-1',
    ts: minus(7),
    speaker: 'stephanie',
    text:
      'Hi, this is Stephanie at NoblePort following up on Highland Phase II. Do you have a moment?',
  },
  {
    id: 't-2',
    ts: minus(6),
    speaker: 'caller',
    text: 'Yes — go ahead. We had architect comments back yesterday.',
  },
  {
    id: 't-3',
    ts: minus(5),
    speaker: 'stephanie',
    text:
      'Got it. I see proposal d-2041 is in proposal stage at $1.24M. I can route the redline to GCagent for repricing.',
    routed: 'GCagent.ai',
  },
  {
    id: 't-4',
    ts: minus(4),
    speaker: 'caller',
    text: 'Please do — and confirm we still have the Q3 slot.',
  },
  {
    id: 't-5',
    ts: minus(3),
    speaker: 'stephanie',
    text:
      'Confirming Q3 mobilization slot is held. Note: deposit must clear before scheduling per policy.',
  },
  {
    id: 't-6',
    ts: minus(1),
    speaker: 'operator',
    text: '(barge-in) Stephanie, also flag this for AR-Collector — INV-0412 is open against this client.',
    routed: 'AR-Collector',
  },
];

// ---------------------------------------------------------------------------
// Sales Intelligence (GPPI v2.0)
//
// Mirrors the backend engine output (backend/sales) for the default snapshot:
// run_simulation(team_size=8, lead_count=40, months_of_real_data=4, seed=42).
// Swap point: replace the body with a fetch to `${API_BASE}/sales/dashboard`.
// ---------------------------------------------------------------------------

export const getSalesIntelligence = (): SalesIntelligence => ({
  version: '2.1',
  truthTag: 'SIMULATED',
  provenance: 'BLENDED',
  label: 'BLENDED MODEL OUTPUT',
  neededNext: 'ACTUAL NOBLEPORT SALES DATASET',
  decisionAuthority: 'Human Review Required',
  generatedAt: NOW_ISO,
  weights: {
    gross_profit: 0.4,
    revenue: 0.25,
    avg_job_size: 0.15,
    close_rate: 0.1,
    lead_response_time: 0.05,
    customer_satisfaction: 0.05,
  },
  headline: {
    grossProfit: 1_315_523,
    revenue: 4_520_256,
    grossMarginPct: 0.291,
    averageJobSize: 85_013,
    avgCloseRate: 0.424,
  },
  leaderboard: [
    { repId: 'rep-06', name: 'Sofia Marchetti', gppi: 94.7, rank: 1, percentile: 1.0, grossProfit: 370_306, revenue: 1_176_397, avgJobSize: 98_033, closeRate: 0.923, leadResponseHours: 2.3, csat: 4.63, topPerformer: true },
    { repId: 'rep-02', name: 'Jordan Pell', gppi: 46.4, rank: 2, percentile: 0.857, grossProfit: 193_980, revenue: 601_479, avgJobSize: 120_296, closeRate: 0.312, leadResponseHours: 4.9, csat: 4.61, topPerformer: true },
    { repId: 'rep-05', name: 'Andre Beaumont', gppi: 33.8, rank: 3, percentile: 0.714, grossProfit: 148_025, revenue: 601_573, avgJobSize: 66_841, closeRate: 0.562, leadResponseHours: 1.9, csat: 4.07, topPerformer: false },
    { repId: 'rep-08', name: 'Tom Castellano', gppi: 32.0, rank: 4, percentile: 0.571, grossProfit: 139_402, revenue: 459_456, avgJobSize: 114_864, closeRate: 0.25, leadResponseHours: 5.0, csat: 4.47, topPerformer: false },
    { repId: 'rep-07', name: 'Wes Coleman', gppi: 30.1, rank: 5, percentile: 0.429, grossProfit: 118_011, revenue: 504_069, avgJobSize: 100_814, closeRate: 0.417, leadResponseHours: 3.1, csat: 4.02, topPerformer: false },
    { repId: 'rep-01', name: "Liam O'Donnell", gppi: 19.8, rank: 6, percentile: 0.286, grossProfit: 130_984, revenue: 474_235, avgJobSize: 79_039, closeRate: 0.286, leadResponseHours: 5.1, csat: 3.59, topPerformer: false },
    { repId: 'rep-04', name: 'Grace Yun', gppi: 16.8, rank: 7, percentile: 0.143, grossProfit: 135_440, revenue: 406_907, avgJobSize: 50_863, closeRate: 0.381, leadResponseHours: 5.8, csat: 4.35, topPerformer: false },
    { repId: 'rep-03', name: 'Priya Anand', gppi: 6.9, rank: 8, percentile: 0.0, grossProfit: 79_375, revenue: 296_141, avgJobSize: 49_357, closeRate: 0.261, leadResponseHours: 3.8, csat: 4.45, topPerformer: false },
  ],
  hierarchy: [
    { key: 'adu', name: 'ADUs', tier: 1, rank: 1, leadFeeder: false, typicalJobMid: 302_500 },
    { key: 'addition', name: 'Additions', tier: 1, rank: 2, leadFeeder: false, typicalJobMid: 250_000 },
    { key: 'design_build', name: 'Design-Build', tier: 1, rank: 3, leadFeeder: false, typicalJobMid: 375_000 },
    { key: 'investor_redevelopment', name: 'Investor Redevelopment', tier: 1, rank: 4, leadFeeder: false, typicalJobMid: 550_000 },
    { key: 'property_acquisition', name: 'Property Acquisition Services', tier: 1, rank: 5, leadFeeder: false, typicalJobMid: 175_000 },
    { key: 'roofing', name: 'Roofing', tier: 2, rank: 6, leadFeeder: true, typicalJobMid: 51_500 },
    { key: 'exterior_restoration', name: 'Exterior Restoration', tier: 2, rank: 7, leadFeeder: false, typicalJobMid: 82_500 },
    { key: 'whole_house_renovation', name: 'Whole House Renovations', tier: 2, rank: 8, leadFeeder: false, typicalJobMid: 270_000 },
    { key: 'kitchen', name: 'Kitchens', tier: 3, rank: 9, leadFeeder: true, typicalJobMid: 77_500 },
    { key: 'bathroom', name: 'Bathrooms', tier: 3, rank: 10, leadFeeder: true, typicalJobMid: 28_500 },
    { key: 'maintenance_membership', name: 'Maintenance Memberships', tier: 4, rank: 11, leadFeeder: true, typicalJobMid: 3_600 },
    { key: 'painting', name: 'Painting', tier: 4, rank: 12, leadFeeder: true, typicalJobMid: 14_500 },
    { key: 'property_services', name: 'Property Services', tier: 4, rank: 13, leadFeeder: true, typicalJobMid: 6_400 },
  ],
  routing: { premium: 25, standard: 15, topPerformers: 2, developingStaff: 6 },
  markets: [
    { town: 'Newburyport', leads: 3, premium: 3, standard: 0 },
    { town: 'Ipswich', leads: 9, premium: 4, standard: 5 },
    { town: 'Manchester-by-the-Sea', leads: 6, premium: 6, standard: 0 },
    { town: 'Essex', leads: 6, premium: 4, standard: 2 },
    { town: 'Marblehead', leads: 7, premium: 4, standard: 3 },
    { town: 'Portsmouth', leads: 2, premium: 2, standard: 0 },
    { town: 'Rye', leads: 2, premium: 1, standard: 1 },
    { town: 'New Castle', leads: 5, premium: 1, standard: 4 },
  ],
  readiness: {
    monthsOfRealData: 4,
    mode: 'simulation_primary',
    realDataWeight: 0.333,
    nextMilestone:
      'Capture the full opportunity→deposit→completion funnel; reach 6 months of data to blend.',
  },
  capture: {
    provenance: 'BLENDED',
    monthsOfRealData: 4,
    capturedOpportunities: 72,
    capturedCompletions: 6,
    realDataWeight: 0.2,
    blockingGaps: [
      '4/12 months of production data',
      '72/200 captured opportunities',
      '6/30 completed projects with realized GP',
    ],
    nextAction: 'Keep capturing the full funnel — close the gaps below to reach ACTUAL.',
  },
  closeRate: {
    baselineLow: 0.0625,
    baselineHigh: 0.125,
    current: 0.0938,
    projected: 0.1794,
    ceiling: 0.45,
    levers: [
      { key: 'response_time', name: 'Sub-hour lead response', owner: 'Stephanie.ai', lift: 0.18, runningRate: 0.1106 },
      { key: 'lead_routing', name: '80/20 profitable-lead routing', owner: 'Sales OS', lift: 0.15, runningRate: 0.1272 },
      { key: 'follow_up', name: 'Disciplined multi-touch follow-up', owner: 'Sales OS', lift: 0.12, runningRate: 0.1425 },
      { key: 'estimate_speed', name: '48-hour estimate turnaround', owner: 'GCagent.ai', lift: 0.1, runningRate: 0.1567 },
      { key: 'gppi_coaching', name: 'GPPI-driven rep coaching', owner: 'Sales OS', lift: 0.08, runningRate: 0.1693 },
      { key: 'proof_trust', name: 'Permit/compliance proof at proposal', owner: 'PermitStream.ai', lift: 0.06, runningRate: 0.1794 },
    ],
  },
  governance: [
    { action: 'route_lead', gate: 'auto', truthTag: 'LIVE', rationale: 'Internal assignment; reversible.' },
    { action: 'score_reps', gate: 'auto', truthTag: 'LIVE', rationale: 'Read-only analytics.' },
    { action: 'suggest_follow_up', gate: 'auto', truthTag: 'LIVE', rationale: 'Advisory nudge only.' },
    { action: 'draft_proposal', gate: 'auto', truthTag: 'LIVE', rationale: 'Draft-state, not sent.' },
    { action: 'reassign_lead', gate: 'human', truthTag: 'STAGED', rationale: "Alters a rep's pipeline / comp." },
    { action: 'apply_discount', gate: 'human', truthTag: 'STAGED', rationale: 'Touches margin and price.' },
    { action: 'send_proposal', gate: 'human', truthTag: 'STAGED', rationale: 'External commitment to a client.' },
    { action: 'approve_contract', gate: 'human', truthTag: 'STAGED', rationale: 'Binds NoblePort; deposit gate.' },
    { action: 'override_gppi_rank', gate: 'human', truthTag: 'STAGED', rationale: 'Overrides measured performance.' },
    { action: 'tax_advisory', gate: 'human', truthTag: 'STAGED', rationale: 'Advisory only; CPA review required.' },
  ],
  collaboration: [
    { trigger: 'New lead captured', from: 'Stephanie.ai', to: 'Sales OS', payload: ['contact', 'town', 'project_type', 'lead_value', 'response_time'], humanGated: false },
    { trigger: 'Lead graded & routed', from: 'Sales OS', to: 'Stephanie.ai', payload: ['assigned_rep', 'lead_grade', 'profitability'], humanGated: false },
    { trigger: 'Proposal ready to send', from: 'Sales OS', to: 'GCagent.ai', payload: ['scope', 'estimate', 'gross_margin_floor'], humanGated: true },
    { trigger: 'Permit feasibility check at proposal', from: 'Sales OS', to: 'PermitStream.ai', payload: ['address', 'ahj', 'project_type', 'scope'], humanGated: false },
    { trigger: 'Contract approved & deposit gate', from: 'Sales OS', to: 'GCagent.ai', payload: ['contract_value', 'deposit_required', 'job_handoff'], humanGated: true },
    { trigger: 'Discount / margin override requested', from: 'Sales OS', to: 'Cyborg.ai', payload: ['rep', 'amount', 'margin_impact'], humanGated: true },
    { trigger: 'Every routing & scoring decision', from: 'Sales OS', to: 'Cyborg.ai', payload: ['decision', 'actor', 'truth_tag', 'audit_hash'], humanGated: false },
  ],
});

// ---------------------------------------------------------------------------
// Program Completion (portfolio view)
//
// Mirrors the backend engine output (backend/program/build_report), which
// MEASURES completion from artifacts that actually exist in the repo. Swap
// point: replace the body with a fetch to `${API_BASE}/program`.
// ---------------------------------------------------------------------------

export const getProgramReport = (): ProgramReport => ({
  generatedAt: NOW_ISO,
  generatedFrom: 'filesystem',
  summary: {
    totalProjects: 14,
    complete: 14,
    inProgress: 0,
    planned: 0,
    overallCompletion: 1.0,
  },
  byCategory: [
    { category: 'Platform', projects: 2, completion: 1.0 },
    { category: 'Revenue', projects: 2, completion: 1.0 },
    { category: 'Governance', projects: 3, completion: 1.0 },
    { category: 'Construction', projects: 2, completion: 1.0 },
    { category: 'Real Estate', projects: 1, completion: 1.0 },
    { category: 'Tokenization', projects: 1, completion: 1.0 },
    { category: 'Trading', projects: 1, completion: 1.0 },
    { category: 'Integration', projects: 1, completion: 1.0 },
    { category: 'Strategy', projects: 1, completion: 1.0 },
  ],
  dimensionCoverage: [
    { dimension: 'backend', projects: 12 },
    { dimension: 'api', projects: 9 },
    { dimension: 'ui', projects: 8 },
    { dimension: 'tests', projects: 8 },
    { dimension: 'docs', projects: 7 },
    { dimension: 'contract', projects: 2 },
  ],
  projects: [
    {
      key: 'buildertrend',
      name: 'Buildertrend Integration',
      summary: 'Two-way CRM/project sync with the Buildertrend platform.',
      category: 'Integration',
      owner: 'Sync Engine',
      since: 'Revenue Spine',
      completion: 1.0,
      status: 'complete',
      delivered: 3,
      total: 3,
      coverage: ['backend', 'api', 'tests'],
      deliverables: [
        { dimension: 'backend', label: 'Buildertrend client + sync engine', satisfied: true, path: 'backend/integrations/buildertrend_client.py' },
        { dimension: 'api', label: 'Buildertrend + sync API', satisfied: true, path: 'backend/api/buildertrend.py' },
        { dimension: 'tests', label: 'Integration tests', satisfied: true, path: 'backend/tests/test_buildertrend.py' },
      ],
    },
    {
      key: 'compliance_audit',
      name: 'Compliance & Audit Chain',
      summary: 'Cyborg compliance alerts and hash-linked audit ledger.',
      category: 'Governance',
      owner: 'Cyborg.ai',
      since: 'Mission Control',
      completion: 1.0,
      status: 'complete',
      delivered: 3,
      total: 3,
      coverage: ['backend', 'api', 'ui'],
      deliverables: [
        { dimension: 'backend', label: 'Cyborg agent + trust records', satisfied: true, path: 'backend/agents/cyborg.py' },
        { dimension: 'ui', label: 'Compliance + audit dashboards', satisfied: true, path: 'src/app/dashboard/compliance/page.tsx' },
        { dimension: 'api', label: 'Audit + compliance feeds', satisfied: true, path: 'src/app/api/v1/dashboard/audit/route.ts' },
      ],
    },
    {
      key: 'tokenization',
      name: 'ERC-1400 Tokenization',
      summary: 'White-label NBPT/USDC security token + smart-contract registry.',
      category: 'Tokenization',
      owner: 'Cyborg.ai',
      since: 'Tokenization',
      completion: 1.0,
      status: 'complete',
      delivered: 4,
      total: 4,
      coverage: ['ui', 'docs', 'contract'],
      deliverables: [
        { dimension: 'contract', label: 'NBPT security token', satisfied: true, path: 'contracts/NBPTSecurityToken1400.sol' },
        { dimension: 'contract', label: 'Human approval gateway', satisfied: true, path: 'contracts/HumanApprovalGateway.sol' },
        { dimension: 'docs', label: 'Token + registry docs', satisfied: true, path: 'docs/tokenization/erc1400-nbpt-usdc.md' },
        { dimension: 'ui', label: 'Token integration hub', satisfied: true, path: 'src/components/StephanieAINetworkHub.tsx' },
      ],
    },
    {
      key: 'mission_control',
      name: 'Mission Control Dashboard',
      summary: 'Operator-grade execution console: KPIs, pipeline, agents, audit.',
      category: 'Platform',
      owner: 'Operator',
      since: 'Mission Control',
      completion: 1.0,
      status: 'complete',
      delivered: 4,
      total: 4,
      coverage: ['backend', 'api', 'ui'],
      deliverables: [
        { dimension: 'ui', label: 'Dashboard shell + pages', satisfied: true, path: 'src/app/dashboard/page.tsx' },
        { dimension: 'backend', label: 'Dashboard contracts + fixtures', satisfied: true, path: 'src/lib/dashboard/types.ts' },
        { dimension: 'api', label: 'Dashboard API routes', satisfied: true, path: 'src/app/api/v1/dashboard' },
        { dimension: 'backend', label: 'FastAPI dashboard gateway', satisfied: true, path: 'backend/api/dashboard.py' },
      ],
    },
    {
      key: 'signer_gateway',
      name: 'NemoCLAW Signer Gateway',
      summary: 'Policy-gated signing with circuit breaker and audit trail.',
      category: 'Governance',
      owner: 'Cyborg.ai',
      since: 'NoblePort OS',
      completion: 1.0,
      status: 'complete',
      delivered: 4,
      total: 4,
      coverage: ['backend', 'tests', 'docs'],
      deliverables: [
        { dimension: 'backend', label: 'Signer gateway + policy', satisfied: true, path: 'src/lib/nemoclaw/signer-gateway.ts' },
        { dimension: 'backend', label: 'Circuit breaker + audit', satisfied: true, path: 'src/lib/nemoclaw/circuit-breaker.ts' },
        { dimension: 'tests', label: 'Signer tests', satisfied: true, path: 'src/lib/nemoclaw/__tests__' },
        { dimension: 'docs', label: 'Signer gateway doc', satisfied: true, path: 'docs/nemoclaw' },
      ],
    },
    {
      key: 'nobleport_os',
      name: 'NoblePort OS Architecture',
      summary: 'Agent mesh, revenue loop, and proof-of-trust spine.',
      category: 'Platform',
      owner: 'Orchestrator',
      since: 'NoblePort OS',
      completion: 1.0,
      status: 'complete',
      delivered: 5,
      total: 5,
      coverage: ['backend', 'api'],
      deliverables: [
        { dimension: 'backend', label: 'Agent mesh + orchestrator', satisfied: true, path: 'backend/agents/orchestrator.py' },
        { dimension: 'backend', label: 'Revenue loop', satisfied: true, path: 'backend/core/revenue_loop.py' },
        { dimension: 'backend', label: 'Proof of trust', satisfied: true, path: 'backend/core/proof_of_trust.py' },
        { dimension: 'backend', label: 'OS architecture lib', satisfied: true, path: 'src/lib/nobleport-os/index.ts' },
        { dimension: 'api', label: 'Trust API', satisfied: true, path: 'backend/api/trust.py' },
      ],
    },
    {
      key: 'realty',
      name: 'NoblePort Realty',
      summary: 'Property analysis and investment underwriting.',
      category: 'Real Estate',
      owner: 'GCagent.ai',
      since: 'Realty Module',
      completion: 1.0,
      status: 'complete',
      delivered: 4,
      total: 4,
      coverage: ['backend', 'ui', 'tests', 'docs'],
      deliverables: [
        { dimension: 'backend', label: 'Property analysis lib', satisfied: true, path: 'src/lib/realty/property-analysis.ts' },
        { dimension: 'ui', label: 'Realty dashboard', satisfied: true, path: 'src/app/dashboard/realty/page.tsx' },
        { dimension: 'docs', label: 'Property analysis doc', satisfied: true, path: 'docs/realty/236-high-road-newbury.md' },
        { dimension: 'tests', label: 'Realty tests', satisfied: true, path: 'src/lib/realty/__tests__' },
      ],
    },
    {
      key: 'roofing',
      name: 'NoblePort Roofing',
      summary: 'Fall-protection safety gates and roofing proposal/estimating.',
      category: 'Construction',
      owner: 'GCagent.ai',
      since: 'Roofing Module',
      completion: 1.0,
      status: 'complete',
      delivered: 4,
      total: 4,
      coverage: ['backend', 'ui', 'tests', 'docs'],
      deliverables: [
        { dimension: 'backend', label: 'Fall protection + proposals lib', satisfied: true, path: 'src/lib/roofing/fall-protection.ts' },
        { dimension: 'ui', label: 'Roofing dashboard + proposals', satisfied: true, path: 'src/app/dashboard/roofing/page.tsx' },
        { dimension: 'tests', label: 'Roofing tests', satisfied: true, path: 'src/lib/roofing/__tests__' },
        { dimension: 'docs', label: 'Roofing doc', satisfied: true, path: 'docs/roofing' },
      ],
    },
    {
      key: 'octastack_trader',
      name: 'OctaStack Trader Bot',
      summary: '8-stack EMA + SuperTrend/ADX crypto bot, backtester, MCP server.',
      category: 'Trading',
      owner: 'KUZO',
      since: 'OctaStack Trader',
      completion: 1.0,
      status: 'complete',
      delivered: 4,
      total: 4,
      coverage: ['backend', 'api', 'tests'],
      deliverables: [
        { dimension: 'backend', label: 'Strategy + bot + risk', satisfied: true, path: 'backend/trading/strategy.py' },
        { dimension: 'backend', label: 'Backtester + optimizer', satisfied: true, path: 'backend/trading/backtest.py' },
        { dimension: 'api', label: 'MCP server', satisfied: true, path: 'backend/trading/mcp_server.py' },
        { dimension: 'tests', label: 'Trading tests', satisfied: true, path: 'backend/trading/tests/test_trading.py' },
      ],
    },
    {
      key: 'permitstream',
      name: 'PermitStream',
      summary: 'Massachusetts permit automation and AHJ tracking.',
      category: 'Construction',
      owner: 'PermitStream.ai',
      since: 'NoblePort OS',
      completion: 1.0,
      status: 'complete',
      delivered: 5,
      total: 5,
      coverage: ['backend', 'api', 'ui', 'tests', 'contract'],
      deliverables: [
        { dimension: 'backend', label: 'Permit-stream agent', satisfied: true, path: 'backend/agents/permit_stream.py' },
        { dimension: 'contract', label: 'MA building permits contract', satisfied: true, path: 'contracts/MassachusettsBuildingPermits.sol' },
        { dimension: 'ui', label: 'Permits dashboard', satisfied: true, path: 'src/app/dashboard/permits/page.tsx' },
        { dimension: 'api', label: 'Permits feed', satisfied: true, path: 'src/app/api/v1/dashboard/permits/route.ts' },
        { dimension: 'tests', label: 'Permit tests', satisfied: true, path: 'backend/tests/test_permits.py' },
      ],
    },
    {
      key: 'revenue_engine',
      name: 'Revenue Engine',
      summary: 'Lead → estimate → job → payment → closeout pipeline automation.',
      category: 'Revenue',
      owner: 'GCagent.ai',
      since: 'Revenue Spine',
      completion: 1.0,
      status: 'complete',
      delivered: 4,
      total: 4,
      coverage: ['backend', 'api', 'ui'],
      deliverables: [
        { dimension: 'backend', label: 'Revenue engine service', satisfied: true, path: 'backend/services/revenue_engine.py' },
        { dimension: 'backend', label: 'Revenue spine + models', satisfied: true, path: 'backend/config/revenue_spine.py' },
        { dimension: 'api', label: 'Revenue API', satisfied: true, path: 'backend/api/revenue.py' },
        { dimension: 'ui', label: 'Revenue warboard', satisfied: true, path: 'src/app/dashboard/revenue/page.tsx' },
      ],
    },
    {
      key: 'sales_os',
      name: 'Sales OS v2.1 (GPPI)',
      summary: 'GPPI leaderboard, 80/20 routing, provenance gate, close-rate loop.',
      category: 'Revenue',
      owner: 'Sales OS',
      since: 'Sales v2.1',
      completion: 1.0,
      status: 'complete',
      delivered: 6,
      total: 6,
      coverage: ['backend', 'api', 'ui', 'tests', 'docs'],
      deliverables: [
        { dimension: 'backend', label: 'GPPI + hierarchy + routing', satisfied: true, path: 'backend/sales/gppi.py' },
        { dimension: 'backend', label: 'Provenance + close-rate + governance', satisfied: true, path: 'backend/sales/provenance.py' },
        { dimension: 'api', label: 'Sales API', satisfied: true, path: 'backend/api/sales.py' },
        { dimension: 'ui', label: 'Revenue War Board', satisfied: true, path: 'src/app/dashboard/sales/page.tsx' },
        { dimension: 'tests', label: 'Sales tests', satisfied: true, path: 'backend/tests/test_sales.py' },
        { dimension: 'docs', label: 'Sales model doc', satisfied: true, path: 'docs/sales/nobleport-sales-model-v2.md' },
      ],
    },
    {
      key: 'stephanie_governance',
      name: 'Stephanie.ai Governance v2',
      summary: 'Executable authority matrix, truth-layer tagging, measured metrics.',
      category: 'Governance',
      owner: 'Stephanie.ai',
      since: 'Governance v2',
      completion: 1.0,
      status: 'complete',
      delivered: 6,
      total: 6,
      coverage: ['backend', 'api', 'tests', 'docs'],
      deliverables: [
        { dimension: 'backend', label: 'Authority matrix + gate', satisfied: true, path: 'backend/governance/authority_matrix.py' },
        { dimension: 'backend', label: 'Truth-layer tagging', satisfied: true, path: 'backend/governance/truth_layer.py' },
        { dimension: 'backend', label: 'Measured metrics + scenarios', satisfied: true, path: 'backend/governance/metrics.py' },
        { dimension: 'api', label: 'Governance API', satisfied: true, path: 'backend/api/governance.py' },
        { dimension: 'tests', label: 'Governance tests', satisfied: true, path: 'backend/tests/test_governance.py' },
        { dimension: 'docs', label: 'Architecture v2 doc', satisfied: true, path: 'docs/governance/stephanie-ai-architecture-v2.md' },
      ],
    },
    {
      key: 'strategic_positioning',
      name: 'Strategic Positioning',
      summary: 'Market positioning and go-to-market analysis.',
      category: 'Strategy',
      owner: 'Operator',
      since: 'Strategy',
      completion: 1.0,
      status: 'complete',
      delivered: 1,
      total: 1,
      coverage: ['docs'],
      deliverables: [
        { dimension: 'docs', label: 'Strategic positioning analysis', satisfied: true, path: 'docs/strategy/strategic-positioning.md' },
      ],
    },
  ],
});


// ---------------------------------------------------------------------------
// Systems Truth Registry
//
// Mirrors the backend engine output (backend/systems/build_registry), which
// classifies systems by evidence: repo nodes are MEASURED, externals are
// DECLARED. Swap point: replace the body with a fetch to `${API_BASE}/systems`.
// ---------------------------------------------------------------------------

export const getSystemsRegistry = (): SystemsRegistry => ({
  generatedAt: NOW_ISO,
  hardTruth: '9 of 72 systems are verified live by a named verifier (operator attestation or third-party telemetry). The count grows only through verification events — never by relabeling.',
  controlTruthFloor: '0 external live nodes are controlled from chat. AI control covers coordination, drafting, audit, build specs, code generation, planning, and connected-tool actions only when authorized — never wallets, banks, validators, GPU clusters, payment rails, legal filings, or permits.',
  bankableCore: ['reg:construction_intake', 'reg:scope_estimate_engine', 'reg:proposal_generator', 'reg:awo_flow', 'reg:change_order_ledger', 'reg:invoice_payment_tracking', 'reg:hubspot_router', 'reg:permitstream', 'reg:gcagent_compliance', 'reg:production_board', 'reg:roofing_takeoff', 'reg:kuzo_dashboard'],
  claimedMetrics: [
    { claim: '3,012 CUDA A100/A800 validators', source: 'Avatar 1B deployment artifact', label: 'CLAIMED / needs telemetry proof' },
    { claim: '88ms p95 avatar render latency', source: 'Avatar 1B deployment artifact', label: 'CLAIMED init metric' },
    { claim: '0.02% avatar error rate', source: 'Avatar 1B deployment artifact', label: 'CLAIMED init metric' },
    { claim: '3,212 live nodes by function', source: '80–100B avatar report', label: 'CLAIMED / report-level only' },
    { claim: '112 AI agents', source: 'Stephanie audit / prior architecture', label: 'CLAIMED / not fully enumerated' },
    { claim: "Local 'Meet1000' roster", source: 'CSV in workspace', label: '20 rows only, not 1,000' },
  ],
  verificationQueue: [
    { key: 'reg:unified_wallet', name: 'NoblePort Unified Wallet', declaredCompletionPct: 88, blocking: 'Wallet connect live; execution off', evidenceNeeded: 'Operator attestation of live operation, or independent telemetry' },
    { key: 'reg:stephanie_core', name: 'Stephanie.ai Core Orchestrator', declaredCompletionPct: 81, blocking: 'Human-governed; not autonomous', evidenceNeeded: 'Operator attestation of live operation, or independent telemetry' },
    { key: 'reg:nbpt_contracts', name: 'NBPT Token Contracts', declaredCompletionPct: 75, blocking: 'Mainnet not launched', evidenceNeeded: 'Operator attestation of live operation, or independent telemetry' },
    { key: 'reg:gcagent_compliance', name: 'GCagent Compliance Monitor', declaredCompletionPct: 44, blocking: 'Connector gaps remain', evidenceNeeded: 'Operator attestation of live operation, or independent telemetry' },
    { key: 'reg:permitstream', name: 'PermitStream.ai', declaredCompletionPct: 38, blocking: 'Regional connectors incomplete', evidenceNeeded: 'Operator attestation of live operation, or independent telemetry' },
    { key: 'reg:cyborg_identity', name: 'Cyborg.ai Identity Layer', declaredCompletionPct: 28, blocking: 'Not live', evidenceNeeded: 'Operator attestation of live operation, or independent telemetry' },
    { key: 'reg:awo_flow', name: 'AWO / Authorized Work Order Flow', declaredCompletionPct: null, blocking: 'Operationally useful, needs ledger hardening', evidenceNeeded: 'Harden the work-order ledger to production grade.' },
    { key: 'reg:invoice_payment_tracking', name: 'Invoice & Payment Tracking', declaredCompletionPct: null, blocking: 'Tracking live; payment automation gated', evidenceNeeded: 'Operator attestation of live operation, or independent telemetry' },
    { key: 'reg:change_order_ledger', name: 'Change Order Ledger', declaredCompletionPct: null, blocking: 'Needs production ledger', evidenceNeeded: 'Operator attestation of live operation, or independent telemetry' },
    { key: 'reg:job_cost_tracker', name: 'Job Cost Tracker', declaredCompletionPct: null, blocking: 'Good framework; needs live accounting feed', evidenceNeeded: 'Operator attestation of live operation, or independent telemetry' },
  ],
  verificationLog: [
    { systemKey: 'repo:mission_control', verifier: 'Vercel deployment telemetry (third party)', method: 'third_party_telemetry', verifiedAt: '2026-06-11', expiresAt: '2026-09-09' },
  ],
  summary: {
    totalSystems: 72,
    verified: 9,
    humanGated: 14,
    byBucket: { verified: 9, staged: 47, claimed: 3, demo: 3, planned: 2, blocked: 4, legal_hold: 3, reference: 1 },
  },
  buckets: [
    { bucket: 'verified', definition: 'Verified live by a named, accountable verifier — operator attestation or independent telemetry. Never self-declared by the system itself.', promotionGate: 'Re-verify on a rolling basis; verification evidence expires.', count: 9 },
    { bucket: 'staged', definition: 'Built and measurable — code, tests, and docs exist on disk — but not verified live in production.', promotionGate: 'Deploy to production and capture independent live telemetry.', count: 47 },
    { bucket: 'claimed', definition: "Self-declared status (e.g. a project's own status file). No independent telemetry or third-party evidence.", promotionGate: 'Obtain independent telemetry or third-party attestation; a self-declared status file can never promote itself.', count: 3 },
    { bucket: 'demo', definition: 'Simulation or demonstration output. Explicitly not production; safe for training, forecasting, and scenario planning.', promotionGate: 'Replace generated/demo data with real production records (real IDs, real transactions), then verify.', count: 3 },
    { bucket: 'planned', definition: 'Roadmap / backlog. Not built yet.', promotionGate: 'Build it: code + tests + docs on disk moves it to STAGED.', count: 2 },
    { bucket: 'blocked', definition: 'Not permitted to operate — fail-closed (e.g. execution-restricted lanes, unresolved governance blocks).', promotionGate: 'Resolve the governing block via the authority matrix; human signoff.', count: 4 },
    { bucket: 'legal_hold', definition: 'Operation gated on legal/compliance signoff (regulated securities, licensed-professional domains). Human approval mandatory.', promotionGate: 'Written legal/compliance signoff from licensed counsel.', count: 3 },
    { bucket: 'reference', definition: 'External artifact or dataset referenced by the program but not yet ingested into the repository.', promotionGate: 'Ingest the artifact into the repo so it becomes measurable.', count: 1 },
  ],
  executionPath: [
    { step: 'Construction ops', node: 'repo:nobleport_os', why: 'Agent mesh + revenue loop already staged.' },
    { step: 'Estimating', node: 'repo:revenue_engine', why: 'Lead → estimate → job pipeline staged.' },
    { step: 'Payments', node: 'payments_live', why: 'Deposit gate enforced; human-approved execution.' },
    { step: 'PM control', node: 'repo:buildertrend', why: 'Two-way project sync staged.' },
    { step: 'Audit ledger', node: 'repo:compliance_audit', why: 'Hash-linked chain staged.' },
    { step: 'Regulated RWA / token layers', node: 'nbpt_token_issuance', why: 'Only after written legal signoff.' },
  ],
  systems: [
    {
      key: 'reg:construction_intake',
      name: 'Construction Intake Workflow',
      category: 'Construction',
      bucket: 'verified',
      summary: 'Job intake → scope → invoice',
      evidence: ['Operator register 2026-06-11: LIVE — 95%', 'Declared completion: 95%', 'Strongest real operating module'],
      nextGate: 'Re-verify on a rolling basis; verification evidence expires.',
      source: 'declared:control-register-2026-06-11',
      humanApprovalRequired: false,
      verifiedBy: 'Operator control register, 2026-06-11',
    },
    {
      key: 'reg:construction_orchestration',
      name: 'Construction Orchestration',
      category: 'Construction',
      bucket: 'verified',
      summary: 'Scope, estimates, subs, permit prep, invoices',
      evidence: ['Operator register 2026-06-11: LIVE', 'Running on real GC work'],
      nextGate: 'Re-verify on a rolling basis; verification evidence expires.',
      source: 'declared:control-register-2026-06-11',
      humanApprovalRequired: false,
      verifiedBy: 'Operator control register, 2026-06-11',
    },
    {
      key: 'reg:kuzo_dashboard',
      name: 'KUZO Live Dashboard',
      category: 'Trading',
      bucket: 'verified',
      summary: 'DexScreener feed, trade log, alerts, SQLite',
      evidence: ['Operator register 2026-06-11: LIVE — 95%', 'Declared completion: 95%', 'Read/dashboard control only'],
      nextGate: 'Re-verify on a rolling basis; verification evidence expires.',
      source: 'declared:control-register-2026-06-11',
      humanApprovalRequired: false,
      verifiedBy: 'Operator control register, 2026-06-11',
    },
    {
      key: 'reg:kuzo_safe_swap',
      name: 'KUZO Safe Swap Layer',
      category: 'Trading',
      bucket: 'verified',
      summary: 'Read-only DeFi quote/policy/simulation layer',
      evidence: ['Operator register 2026-06-11: LIVE READ-ONLY — 92%', 'Declared completion: 92%', 'Execution disabled by design'],
      nextGate: 'Scope is read-only; any execution requires all policy gates + human signoff.',
      source: 'declared:control-register-2026-06-11',
      humanApprovalRequired: false,
      verifiedBy: 'Operator control register, 2026-06-11',
    },
    {
      key: 'reg:manual_permit_fallback',
      name: 'Manual Permit Fallback',
      category: 'Construction',
      bucket: 'verified',
      summary: 'Human/manual permit filing support',
      evidence: ['Operator register 2026-06-11: LIVE', 'AI prepares; human files'],
      nextGate: 'Re-verify on a rolling basis; verification evidence expires.',
      source: 'declared:control-register-2026-06-11',
      humanApprovalRequired: true,
      verifiedBy: 'Operator control register, 2026-06-11',
    },
    {
      key: 'repo:mission_control',
      name: 'Mission Control Dashboard',
      category: 'Platform',
      bucket: 'verified',
      summary: 'Operator-grade execution console: KPIs, pipeline, agents, audit.',
      evidence: ['4/4 deliverables on disk (backend, api, ui)', 'measured by backend/program against the filesystem', "Vercel status API: 3/3 production deployments 'completed' on commit 0bfae1d (2026-06-11 20:08 UTC)", 'Projects: nobleport-etf, nobleport-etf-ekqm, cyborio — all Ready and serving', 'Scope: deployed dashboard UI is live; data panels are fixture-backed (MODELED) until the FastAPI gateway is wired'],
      nextGate: 'Re-verify before 2026-09-09 (rolling window).',
      source: 'measured:repo',
      humanApprovalRequired: false,
      verifiedBy: 'Vercel deployment telemetry (third party)',
    },
    {
      key: 'reg:proposal_generator',
      name: 'Proposal Generator',
      category: 'Construction',
      bucket: 'verified',
      summary: 'Roofing, bath, porch, deck, construction proposals',
      evidence: ['Operator register 2026-06-11: LIVE', 'Generates drafts now'],
      nextGate: 'Re-verify on a rolling basis; verification evidence expires.',
      source: 'declared:control-register-2026-06-11',
      humanApprovalRequired: false,
      verifiedBy: 'Operator control register, 2026-06-11',
    },
    {
      key: 'reg:scope_estimate_engine',
      name: 'Scope & Estimate Engine',
      category: 'Construction',
      bucket: 'verified',
      summary: 'AI-assisted scope and pricing',
      evidence: ['Operator register 2026-06-11: LIVE', 'Drafts estimates; Mike approves'],
      nextGate: 'Re-verify on a rolling basis; verification evidence expires.',
      source: 'declared:control-register-2026-06-11',
      humanApprovalRequired: true,
      verifiedBy: 'Operator control register, 2026-06-11',
    },
    {
      key: 'reg:telegram_price_bot',
      name: 'Telegram Price Bot',
      category: 'Trading',
      bucket: 'verified',
      summary: 'Telegram bot serving live price queries.',
      evidence: ["Operator register source header (2026-06-11): 'Telegram Price Bot is LIVE 90%'", 'Declared completion: 90%'],
      nextGate: 'Rolling re-attestation; add uptime telemetry for third-party verification.',
      source: 'declared:control-register-2026-06-11',
      humanApprovalRequired: false,
      verifiedBy: 'Operator control register, 2026-06-11',
    },
    {
      key: 'reg:awo_flow',
      name: 'AWO / Authorized Work Order Flow',
      category: 'Construction',
      bucket: 'staged',
      summary: 'Work order control and job authorization',
      evidence: ['Operator register 2026-06-11: LIVE / STAGED', 'Operationally useful, needs ledger hardening'],
      nextGate: 'Harden the work-order ledger to production grade.',
      source: 'declared:control-register-2026-06-11',
      humanApprovalRequired: false,
      verifiedBy: null,
    },
    {
      key: 'reg:admin_approval_gate',
      name: 'Admin Approval Gate',
      category: 'Governance',
      bucket: 'staged',
      summary: 'Human approval before payouts/actions',
      evidence: ['Operator register 2026-06-11: STAGED', 'Correct risk control'],
      nextGate: 'Deploy to production and capture independent live telemetry.',
      source: 'declared:control-register-2026-06-11',
      humanApprovalRequired: true,
      verifiedBy: null,
    },
    {
      key: 'reg:aragon_dao',
      name: 'Aragon DAO Framework',
      category: 'Governance',
      bucket: 'staged',
      summary: 'DAO execution / role-gated governance',
      evidence: ['Operator register 2026-06-11: STAGED', 'Mainnet deployment pending'],
      nextGate: 'Deploy to production and capture independent live telemetry.',
      source: 'declared:control-register-2026-06-11',
      humanApprovalRequired: false,
      verifiedBy: null,
    },
    {
      key: 'reg:audit_beacon_sol',
      name: 'AuditBeacon.sol',
      category: 'Governance',
      bucket: 'staged',
      summary: 'Smart-contract audit trail concept',
      evidence: ['Operator register 2026-06-11: STAGED', 'No external audit completed'],
      nextGate: 'Deploy to production and capture independent live telemetry.',
      source: 'declared:control-register-2026-06-11',
      humanApprovalRequired: false,
      verifiedBy: null,
    },
    {
      key: 'reg:bidhunter_pro',
      name: 'BidHunter Pro',
      category: 'Revenue',
      bucket: 'staged',
      summary: 'Public/private bid matching',
      evidence: ['Operator register 2026-06-11: STAGED', 'Not live revenue engine yet'],
      nextGate: 'Deploy to production and capture independent live telemetry.',
      source: 'declared:control-register-2026-06-11',
      humanApprovalRequired: false,
      verifiedBy: null,
    },
    {
      key: 'repo:buildertrend',
      name: 'Buildertrend Integration',
      category: 'Integration',
      bucket: 'staged',
      summary: 'Two-way CRM/project sync with the Buildertrend platform.',
      evidence: ['3/3 deliverables on disk (backend, api, tests)', 'measured by backend/program against the filesystem'],
      nextGate: 'Deploy to production and capture independent live telemetry.',
      source: 'measured:repo',
      humanApprovalRequired: false,
      verifiedBy: null,
    },
    {
      key: 'reg:chainlink_oracle',
      name: 'Chainlink Oracle Integration',
      category: 'Network',
      bucket: 'staged',
      summary: 'Price/compliance/oracle triggers',
      evidence: ['Operator register 2026-06-11: STAGED', 'Architecture wired, live feeds not proven'],
      nextGate: 'Deploy to production and capture independent live telemetry.',
      source: 'declared:control-register-2026-06-11',
      humanApprovalRequired: false,
      verifiedBy: null,
    },
    {
      key: 'reg:change_order_ledger',
      name: 'Change Order Ledger',
      category: 'Construction',
      bucket: 'staged',
      summary: 'AWO changes, scope deltas, approvals',
      evidence: ['Operator register 2026-06-11: STAGED', 'Needs production ledger'],
      nextGate: 'Deploy to production and capture independent live telemetry.',
      source: 'declared:control-register-2026-06-11',
      humanApprovalRequired: false,
      verifiedBy: null,
    },
    {
      key: 'repo:compliance_audit',
      name: 'Compliance & Audit Chain',
      category: 'Governance',
      bucket: 'staged',
      summary: 'Cyborg compliance alerts and hash-linked audit ledger.',
      evidence: ['3/3 deliverables on disk (backend, api, ui)', 'measured by backend/program against the filesystem'],
      nextGate: 'Deploy to production and capture independent live telemetry.',
      source: 'measured:repo',
      humanApprovalRequired: false,
      verifiedBy: null,
    },
    {
      key: 'reg:cyborg_identity',
      name: 'Cyborg.ai Identity Layer',
      category: 'Identity',
      bucket: 'staged',
      summary: 'Identity + signing architecture',
      evidence: ['Operator register 2026-06-11: STAGED — 28%', 'Declared completion: 28%', 'Not live'],
      nextGate: 'Deploy to production and capture independent live telemetry.',
      source: 'declared:control-register-2026-06-11',
      humanApprovalRequired: false,
      verifiedBy: null,
    },
    {
      key: 'reg:daily_exec_brief',
      name: 'Daily Executive Brief',
      category: 'Platform',
      bucket: 'staged',
      summary: 'Daily operations summary',
      evidence: ['Operator register 2026-06-11: STAGED', 'Needs automation connection'],
      nextGate: 'Deploy to production and capture independent live telemetry.',
      source: 'declared:control-register-2026-06-11',
      humanApprovalRequired: false,
      verifiedBy: null,
    },
    {
      key: 'reg:deck_porch_agent',
      name: 'Deck / Porch Design Agent',
      category: 'Construction',
      bucket: 'staged',
      summary: 'Decks, porches, drawings, bid scopes',
      evidence: ['Operator register 2026-06-11: STAGED', 'Needs engineering + code validation'],
      nextGate: 'Deploy to production and capture independent live telemetry.',
      source: 'declared:control-register-2026-06-11',
      humanApprovalRequired: false,
      verifiedBy: null,
    },
    {
      key: 'reg:design_build_bid',
      name: 'Design-Build Bid System',
      category: 'Revenue',
      bucket: 'staged',
      summary: 'Design-build estimating and bid packs',
      evidence: ['Operator register 2026-06-11: STAGED', 'Needs persistent app wiring'],
      nextGate: 'Deploy to production and capture independent live telemetry.',
      source: 'declared:control-register-2026-06-11',
      humanApprovalRequired: false,
      verifiedBy: null,
    },
    {
      key: 'repo:tokenization',
      name: 'ERC-1400 Tokenization',
      category: 'Tokenization',
      bucket: 'staged',
      summary: 'White-label NBPT/USDC security token + smart-contract registry.',
      evidence: ['4/4 deliverables on disk (ui, docs, contract)', 'measured by backend/program against the filesystem'],
      nextGate: 'Deploy to production and capture independent live telemetry.',
      source: 'measured:repo',
      humanApprovalRequired: false,
      verifiedBy: null,
    },
    {
      key: 'reg:gcagent_compliance',
      name: 'GCagent Compliance Monitor',
      category: 'Governance',
      bucket: 'staged',
      summary: 'Flags compliance state and anomalies',
      evidence: ['Operator register 2026-06-11: STAGED — 44%', 'Declared completion: 44%', 'Connector gaps remain'],
      nextGate: 'Deploy to production and capture independent live telemetry.',
      source: 'declared:control-register-2026-06-11',
      humanApprovalRequired: false,
      verifiedBy: null,
    },
    {
      key: 'reg:gcagent',
      name: 'GCagent.ai',
      category: 'Construction',
      bucket: 'staged',
      summary: 'General contractor coordination',
      evidence: ['Operator register 2026-06-11: STAGED', 'Can advise/control workflow, not execute field actions'],
      nextGate: 'Deploy to production and capture independent live telemetry.',
      source: 'declared:control-register-2026-06-11',
      humanApprovalRequired: false,
      verifiedBy: null,
    },
    {
      key: 'reg:hubspot_router',
      name: 'HubSpot / CRM Router',
      category: 'Integration',
      bucket: 'staged',
      summary: 'Lead intake and sales routing',
      evidence: ['Operator register 2026-06-11: STAGED / PARTIAL', 'Reauth/writes need verification'],
      nextGate: 'Deploy to production and capture independent live telemetry.',
      source: 'declared:control-register-2026-06-11',
      humanApprovalRequired: false,
      verifiedBy: null,
    },
    {
      key: 'reg:ipfs_arweave_anchoring',
      name: 'IPFS / Arweave Anchoring',
      category: 'Network',
      bucket: 'staged',
      summary: 'Audit log and metadata anchoring',
      evidence: ['Operator register 2026-06-11: STAGED / PARTIAL', 'Claims exist; needs proof hashes per event'],
      nextGate: 'Produce verifiable proof hashes per anchored event.',
      source: 'declared:control-register-2026-06-11',
      humanApprovalRequired: false,
      verifiedBy: null,
    },
    {
      key: 'reg:invoice_payment_tracking',
      name: 'Invoice & Payment Tracking',
      category: 'Payments',
      bucket: 'staged',
      summary: 'Job billing and payment status',
      evidence: ['Operator register 2026-06-11: LIVE / STAGED', 'Tracking live; payment automation gated'],
      nextGate: 'Deploy to production and capture independent live telemetry.',
      source: 'declared:control-register-2026-06-11',
      humanApprovalRequired: true,
      verifiedBy: null,
    },
    {
      key: 'reg:job_cost_tracker',
      name: 'Job Cost Tracker',
      category: 'Construction',
      bucket: 'staged',
      summary: 'Labor/material/sub cost control',
      evidence: ['Operator register 2026-06-11: STAGED', 'Good framework; needs live accounting feed'],
      nextGate: 'Deploy to production and capture independent live telemetry.',
      source: 'declared:control-register-2026-06-11',
      humanApprovalRequired: false,
      verifiedBy: null,
    },
    {
      key: 'reg:kuzo_policy_engine',
      name: 'KUZO Policy Engine',
      category: 'Trading',
      bucket: 'staged',
      summary: 'Allowlists, slippage, price impact, notional caps',
      evidence: ['Operator register 2026-06-11: LIVE / PARTIAL', '3/10 gates passed'],
      nextGate: 'Pass the remaining 7/10 policy gates.',
      source: 'declared:control-register-2026-06-11',
      humanApprovalRequired: false,
      verifiedBy: null,
    },
    {
      key: 'reg:lead_command_pipeline',
      name: 'Lead Command / Trust Pipeline',
      category: 'Revenue',
      bucket: 'staged',
      summary: 'Lead → estimate → close workflow',
      evidence: ['Operator register 2026-06-11: STAGED', 'Strong operating design'],
      nextGate: 'Deploy to production and capture independent live telemetry.',
      source: 'declared:control-register-2026-06-11',
      humanApprovalRequired: false,
      verifiedBy: null,
    },
    {
      key: 'reg:mercury_reconciliation',
      name: 'Mercury Reconciliation',
      category: 'Payments',
      bucket: 'staged',
      summary: 'Bank feed / cash control',
      evidence: ['Operator register 2026-06-11: STAGED', 'Needs verified live connection'],
      nextGate: 'Deploy to production and capture independent live telemetry.',
      source: 'declared:control-register-2026-06-11',
      humanApprovalRequired: false,
      verifiedBy: null,
    },
    {
      key: 'reg:nbpt_contracts',
      name: 'NBPT Token Contracts',
      category: 'Tokenization',
      bucket: 'staged',
      summary: 'ERC-1400 token contract architecture',
      evidence: ['Operator register 2026-06-11: STAGED — 75%', 'Declared completion: 75%', 'Mainnet not launched'],
      nextGate: 'Deploy to production and capture independent live telemetry.',
      source: 'declared:control-register-2026-06-11',
      humanApprovalRequired: false,
      verifiedBy: null,
    },
    {
      key: 'reg:nbpt_token_economy',
      name: 'NBPT Token Economy',
      category: 'Tokenization',
      bucket: 'staged',
      summary: 'Staking, governance, access gating',
      evidence: ['Operator register 2026-06-11: STAGED', 'No public token sale verified'],
      nextGate: 'Deploy to production and capture independent live telemetry.',
      source: 'declared:control-register-2026-06-11',
      humanApprovalRequired: false,
      verifiedBy: null,
    },
    {
      key: 'repo:signer_gateway',
      name: 'NemoCLAW Signer Gateway',
      category: 'Governance',
      bucket: 'staged',
      summary: 'Policy-gated signing with circuit breaker and audit trail.',
      evidence: ['4/4 deliverables on disk (backend, tests, docs)', 'measured by backend/program against the filesystem'],
      nextGate: 'Deploy to production and capture independent live telemetry.',
      source: 'measured:repo',
      humanApprovalRequired: false,
      verifiedBy: null,
    },
    {
      key: 'repo:nobleport_os',
      name: 'NoblePort OS Architecture',
      category: 'Platform',
      bucket: 'staged',
      summary: 'Agent mesh, revenue loop, and proof-of-trust spine.',
      evidence: ['5/5 deliverables on disk (backend, api)', 'measured by backend/program against the filesystem'],
      nextGate: 'Deploy to production and capture independent live telemetry.',
      source: 'measured:repo',
      humanApprovalRequired: false,
      verifiedBy: null,
    },
    {
      key: 'repo:realty',
      name: 'NoblePort Realty',
      category: 'Real Estate',
      bucket: 'staged',
      summary: 'Property analysis and investment underwriting.',
      evidence: ['4/4 deliverables on disk (backend, ui, tests, docs)', 'measured by backend/program against the filesystem'],
      nextGate: 'Deploy to production and capture independent live telemetry.',
      source: 'measured:repo',
      humanApprovalRequired: false,
      verifiedBy: null,
    },
    {
      key: 'repo:roofing',
      name: 'NoblePort Roofing',
      category: 'Construction',
      bucket: 'staged',
      summary: 'Fall-protection safety gates and roofing proposal/estimating.',
      evidence: ['4/4 deliverables on disk (backend, ui, tests, docs)', 'measured by backend/program against the filesystem'],
      nextGate: 'Deploy to production and capture independent live telemetry.',
      source: 'measured:repo',
      humanApprovalRequired: false,
      verifiedBy: null,
    },
    {
      key: 'reg:unified_wallet',
      name: 'NoblePort Unified Wallet',
      category: 'Tokenization',
      bucket: 'staged',
      summary: 'MetaMask + Phantom wallet interface',
      evidence: ['Operator register 2026-06-11: STAGED — 88%', 'Declared completion: 88%', 'Wallet connect live; execution off'],
      nextGate: 'Deploy to production and capture independent live telemetry.',
      source: 'declared:control-register-2026-06-11',
      humanApprovalRequired: false,
      verifiedBy: null,
    },
    {
      key: 'repo:octastack_trader',
      name: 'OctaStack Trader Bot',
      category: 'Trading',
      bucket: 'staged',
      summary: '8-stack EMA + SuperTrend/ADX crypto bot, backtester, MCP server.',
      evidence: ['4/4 deliverables on disk (backend, api, tests)', 'measured by backend/program against the filesystem'],
      nextGate: 'Deploy to production and capture independent live telemetry.',
      source: 'measured:repo',
      humanApprovalRequired: false,
      verifiedBy: null,
    },
    {
      key: 'reg:pmagent',
      name: 'PMagent',
      category: 'Construction',
      bucket: 'staged',
      summary: 'Construction operations controller',
      evidence: ['Operator register 2026-06-11: STAGED', 'No autonomous approvals'],
      nextGate: 'Deploy to production and capture independent live telemetry.',
      source: 'declared:control-register-2026-06-11',
      humanApprovalRequired: true,
      verifiedBy: null,
    },
    {
      key: 'repo:permitstream',
      name: 'PermitStream',
      category: 'Construction',
      bucket: 'staged',
      summary: 'Massachusetts permit automation and AHJ tracking.',
      evidence: ['5/5 deliverables on disk (backend, api, ui, tests, contract)', 'measured by backend/program against the filesystem'],
      nextGate: 'Deploy to production and capture independent live telemetry.',
      source: 'measured:repo',
      humanApprovalRequired: false,
      verifiedBy: null,
    },
    {
      key: 'reg:permitstream',
      name: 'PermitStream.ai',
      category: 'Construction',
      bucket: 'staged',
      summary: 'Permit prep, zoning, compliance docs',
      evidence: ['Operator register 2026-06-11: STAGED — 38%', 'Declared completion: 38%', 'Regional connectors incomplete'],
      nextGate: 'Deploy to production and capture independent live telemetry.',
      source: 'declared:control-register-2026-06-11',
      humanApprovalRequired: false,
      verifiedBy: null,
    },
    {
      key: 'reg:production_board',
      name: 'Production Board',
      category: 'Construction',
      bucket: 'staged',
      summary: 'Milestones, punch lists, project status',
      evidence: ['Operator register 2026-06-11: STAGED / LIVE PARTIAL', 'Useful manually now'],
      nextGate: 'Deploy to production and capture independent live telemetry.',
      source: 'declared:control-register-2026-06-11',
      humanApprovalRequired: false,
      verifiedBy: null,
    },
    {
      key: 'repo:revenue_engine',
      name: 'Revenue Engine',
      category: 'Revenue',
      bucket: 'staged',
      summary: 'Lead → estimate → job → payment → closeout pipeline automation.',
      evidence: ['4/4 deliverables on disk (backend, api, ui)', 'measured by backend/program against the filesystem'],
      nextGate: 'Deploy to production and capture independent live telemetry.',
      source: 'measured:repo',
      humanApprovalRequired: false,
      verifiedBy: null,
    },
    {
      key: 'reg:roofing_takeoff',
      name: 'Roofing Takeoff Module',
      category: 'Construction',
      bucket: 'staged',
      summary: 'Squares, ridge, flashing, skylight, rubber',
      evidence: ['Operator register 2026-06-11: STAGED / MANUAL LIVE', 'Calculations work; app module not fully deployed'],
      nextGate: 'Deploy to production and capture independent live telemetry.',
      source: 'declared:control-register-2026-06-11',
      humanApprovalRequired: false,
      verifiedBy: null,
    },
    {
      key: 'repo:sales_os',
      name: 'Sales OS v2.1 (GPPI)',
      category: 'Revenue',
      bucket: 'staged',
      summary: 'GPPI leaderboard, 80/20 routing, provenance gate, close-rate loop.',
      evidence: ['6/6 deliverables on disk (backend, api, ui, tests, docs)', 'measured by backend/program against the filesystem'],
      nextGate: 'Deploy to production and capture independent live telemetry.',
      source: 'measured:repo',
      humanApprovalRequired: false,
      verifiedBy: null,
    },
    {
      key: 'reg:snapshot_governance',
      name: 'Snapshot Governance',
      category: 'Governance',
      bucket: 'staged',
      summary: 'DAO voting and proposal records',
      evidence: ['Operator register 2026-06-11: STAGED', 'Not full mainnet governance'],
      nextGate: 'Deploy to production and capture independent live telemetry.',
      source: 'declared:control-register-2026-06-11',
      humanApprovalRequired: false,
      verifiedBy: null,
    },
    {
      key: 'reg:stephanie_voice_video',
      name: 'Stephanie Voice & Video Layer',
      category: 'Platform',
      bucket: 'staged',
      summary: 'TTS, avatar, WebRTC, calls, video',
      evidence: ['Operator register 2026-06-11: STAGED', 'Feature set documented, production voice not complete'],
      nextGate: 'Deploy to production and capture independent live telemetry.',
      source: 'declared:control-register-2026-06-11',
      humanApprovalRequired: false,
      verifiedBy: null,
    },
    {
      key: 'reg:stephanie_core',
      name: 'Stephanie.ai Core Orchestrator',
      category: 'Platform',
      bucket: 'staged',
      summary: 'Routes work, proposes workflows, logs decisions',
      evidence: ['Operator register 2026-06-11: STAGED — 81%', 'Declared completion: 81%', 'Human-governed; not autonomous'],
      nextGate: 'Deploy to production and capture independent live telemetry.',
      source: 'declared:control-register-2026-06-11',
      humanApprovalRequired: false,
      verifiedBy: null,
    },
    {
      key: 'repo:stephanie_governance',
      name: 'Stephanie.ai Governance v2',
      category: 'Governance',
      bucket: 'staged',
      summary: 'Executable authority matrix, truth-layer tagging, measured metrics.',
      evidence: ['6/6 deliverables on disk (backend, api, tests, docs)', 'measured by backend/program against the filesystem'],
      nextGate: 'Deploy to production and capture independent live telemetry.',
      source: 'measured:repo',
      humanApprovalRequired: false,
      verifiedBy: null,
    },
    {
      key: 'repo:strategic_positioning',
      name: 'Strategic Positioning',
      category: 'Strategy',
      bucket: 'staged',
      summary: 'Market positioning and go-to-market analysis.',
      evidence: ['1/1 deliverables on disk (docs)', 'measured by backend/program against the filesystem'],
      nextGate: 'Deploy to production and capture independent live telemetry.',
      source: 'measured:repo',
      humanApprovalRequired: false,
      verifiedBy: null,
    },
    {
      key: 'reg:stripe_mercury_node',
      name: 'Stripe / Mercury Payment Node',
      category: 'Payments',
      bucket: 'staged',
      summary: 'Construction-only payment spine',
      evidence: ['Operator register 2026-06-11: STAGED / P0 HARDENED', 'Production-gated; not full ledger production'],
      nextGate: 'Deploy to production and capture independent live telemetry.',
      source: 'declared:control-register-2026-06-11',
      humanApprovalRequired: true,
      verifiedBy: null,
    },
    {
      key: 'payments_live',
      name: 'Stripe Payment Execution',
      category: 'Payments',
      bucket: 'staged',
      summary: 'Stripe service wired into the revenue engine; deposit gate enforced in code.',
      evidence: ['backend/services/stripe_service.py + payments API on disk', 'Payment approval is a HUMAN-gated action in the governance matrix'],
      nextGate: 'Live keys + first verified production transaction with human approval.',
      source: 'measured:repo',
      humanApprovalRequired: true,
      verifiedBy: null,
    },
    {
      key: 'reg:jsonl_ledger',
      name: 'Tamper-Evident JSONL Ledger',
      category: 'Payments',
      bucket: 'staged',
      summary: 'Append-only fallback ledger',
      evidence: ['Operator register 2026-06-11: STAGED', 'Must migrate to Postgres/Supabase'],
      nextGate: 'Deploy to production and capture independent live telemetry.',
      source: 'declared:control-register-2026-06-11',
      humanApprovalRequired: false,
      verifiedBy: null,
    },
    {
      key: 'reg:zksbt_identity',
      name: 'zkSBT Identity Framework',
      category: 'Identity',
      bucket: 'staged',
      summary: 'Identity, roles, gated access',
      evidence: ['Operator register 2026-06-11: STAGED', 'Holder counts are targets, not current live proof'],
      nextGate: 'Deploy to production and capture independent live telemetry.',
      source: 'declared:control-register-2026-06-11',
      humanApprovalRequired: false,
      verifiedBy: null,
    },
    {
      key: 'epochx_mesh',
      name: 'EpochX Mesh / Validator Network',
      category: 'Network',
      bucket: 'claimed',
      summary: 'Status file claims mesh launched, 1,000 active validators, stream live, agi_mode ON.',
      evidence: ['Self-declared project status file only', 'No independent validator telemetry or third-party attestation'],
      nextGate: 'Independent validator telemetry / third-party attestation; a status file cannot promote itself.',
      source: 'declared:epochx-status-file',
      humanApprovalRequired: false,
      verifiedBy: null,
    },
    {
      key: 'reg:avatar_gpu_layer',
      name: 'Stephanie Avatar GPU Layer',
      category: 'Network',
      bucket: 'claimed',
      summary: 'Voice/prosody, emotion, lip-sync, gesture, GPU optimization',
      evidence: ['Operator register 2026-06-11: CLAIMED / NOT INDEPENDENTLY VERIFIED', 'Deployment artifact claims 3,012 validators and 88ms p95 render latency'],
      nextGate: 'Obtain independent telemetry or third-party attestation; a self-declared status file can never promote itself.',
      source: 'declared:control-register-2026-06-11',
      humanApprovalRequired: false,
      verifiedBy: null,
    },
    {
      key: 'reg:zk_kyt_compliance',
      name: 'zk-KYT Compliance Layer',
      category: 'Governance',
      bucket: 'claimed',
      summary: 'Transaction compliance screening concept',
      evidence: ['Operator register 2026-06-11: STAGED / CLAIMED', 'Needs third-party audit'],
      nextGate: 'Third-party audit of the screening claims.',
      source: 'declared:control-register-2026-06-11',
      humanApprovalRequired: false,
      verifiedBy: null,
    },
    {
      key: 'avatar_fleet',
      name: 'Avatar Deployment Fleet',
      category: 'Network',
      bucket: 'demo',
      summary: 'Summary reports 2,000,000 deployment tasks completed in 7.33s.',
      evidence: ['Artifact itself states avatar IDs/features were randomly generated for demonstration', 'Throughput figure describes a local loop, not production infrastructure'],
      nextGate: 'Production deployment records with real, non-generated identities; then verify.',
      source: 'declared:avatar-deployment-summary',
      humanApprovalRequired: false,
      verifiedBy: null,
    },
    {
      key: 'reg:sales_sim_layer',
      name: 'Sales Agent Simulation Layer',
      category: 'Revenue',
      bucket: 'demo',
      summary: 'Rep simulation, training, close-rate modeling',
      evidence: ['Operator register 2026-06-11: SIMULATED', 'Useful training model, not real reps'],
      nextGate: 'Replace generated/demo data with real production records (real IDs, real transactions), then verify.',
      source: 'declared:control-register-2026-06-11',
      humanApprovalRequired: false,
      verifiedBy: null,
    },
    {
      key: 'sales_simulation',
      name: 'Sales Simulation (GPPI v2.1)',
      category: 'Revenue',
      bucket: 'demo',
      summary: 'Deterministic seeded team + lead-board simulation; SIMULATED truth tag on every output.',
      evidence: ['backend/sales engine, 40 tests; outputs carry SIMULATED tag', 'Data-provenance gate tracks SIMULATED → BLENDED → ACTUAL'],
      nextGate: 'Capture the real opportunity→deposit→completion funnel (capture-first provenance gate).',
      source: 'measured:repo',
      humanApprovalRequired: false,
      verifiedBy: null,
    },
    {
      key: 'reg:postgres_ledger',
      name: 'Postgres / Supabase Ledger',
      category: 'Payments',
      bucket: 'planned',
      summary: 'Production-grade accounting ledger',
      evidence: ['Operator register 2026-06-11: TARGET', 'Not complete'],
      nextGate: 'Build it: code + tests + docs on disk moves it to STAGED.',
      source: 'declared:control-register-2026-06-11',
      humanApprovalRequired: false,
      verifiedBy: null,
    },
    {
      key: 'reg:stripe_live_mode',
      name: 'Stripe Live Mode Integration',
      category: 'Payments',
      bucket: 'planned',
      summary: 'Live payment processing',
      evidence: ['Operator register 2026-06-11: TARGET / GATED', 'Needs real keys, webhook, legal controls'],
      nextGate: 'Build it: code + tests + docs on disk moves it to STAGED.',
      source: 'declared:control-register-2026-06-11',
      humanApprovalRequired: true,
      verifiedBy: null,
    },
    {
      key: 'trading_live_execution',
      name: 'OctaStack Live Trading Execution',
      category: 'Trading',
      bucket: 'blocked',
      summary: 'Live order execution for the OctaStack bot. Backtesting is STAGED; live trading is not.',
      evidence: ['KUZO/Trading is an execution-restricted lane in the governance authority matrix', 'Backtester + MCP server staged with 28 passing tests'],
      nextGate: 'Authority-matrix change with human signoff; broker credentials under signer-gateway policy.',
      source: 'measured:repo',
      humanApprovalRequired: true,
      verifiedBy: null,
    },
    {
      key: 'reg:permitstream_monitor',
      name: 'PermitStream Monitor',
      category: 'Construction',
      bucket: 'blocked',
      summary: 'Daily permit scan/digest',
      evidence: ['Operator register 2026-06-11: BLOCKED / STAGED', 'Missing monitor + Slack issue'],
      nextGate: 'Restore the monitor job and Slack alert wiring, then re-stage.',
      source: 'declared:control-register-2026-06-11',
      humanApprovalRequired: false,
      verifiedBy: null,
    },
    {
      key: 'reg:swap_execution',
      name: 'Swap Execution Module',
      category: 'Trading',
      bucket: 'blocked',
      summary: 'Actual on-chain swap execution',
      evidence: ['Operator register 2026-06-11: DISABLED / HOLD', 'Correctly blocked until all gates pass'],
      nextGate: 'Resolve the governing block via the authority matrix; human signoff.',
      source: 'declared:control-register-2026-06-11',
      humanApprovalRequired: true,
      verifiedBy: null,
    },
    {
      key: 'reg:treasury_bot_v3',
      name: 'TreasuryBotV3',
      category: 'Payments',
      bucket: 'blocked',
      summary: 'Auto-compound/yield routing concept',
      evidence: ['Operator register 2026-06-11: HOLD / STAGED', 'No autonomous treasury control'],
      nextGate: 'Autonomous treasury movement is not allowed; requires authority-matrix change + human signoff.',
      source: 'declared:control-register-2026-06-11',
      humanApprovalRequired: true,
      verifiedBy: null,
    },
    {
      key: 'reg:fiat_router',
      name: 'FiatRouter',
      category: 'Payments',
      bucket: 'legal_hold',
      summary: 'Stripe/Mercury → USDC routing concept',
      evidence: ['Operator register 2026-06-11: HOLD / STAGED', 'Construction-only payments until legal review'],
      nextGate: 'Written legal/compliance signoff from licensed counsel.',
      source: 'declared:control-register-2026-06-11',
      humanApprovalRequired: true,
      verifiedBy: null,
    },
    {
      key: 'nbpt_token_issuance',
      name: 'NBPT Security Token Issuance (ERC-1400)',
      category: 'Tokenization',
      bucket: 'legal_hold',
      summary: 'White-label ERC-1400 security token with USDC peg; contracts staged in repo.',
      evidence: ['Contracts on disk (NBPTSecurityToken1400.sol, HumanApprovalGateway.sol)', 'Regulated security — issuance requires securities-counsel signoff', 'Open OpenZeppelin findings: 1 High, 5 Low (pre-existing)'],
      nextGate: 'Written legal signoff + resolve the OZ High finding before any issuance.',
      source: 'measured:repo',
      humanApprovalRequired: true,
      verifiedBy: null,
    },
    {
      key: 'reg:real_estate_nft',
      name: 'RealEstateNFT Engine',
      category: 'Tokenization',
      bucket: 'legal_hold',
      summary: 'ERC-721 property/title/rent concept',
      evidence: ['Operator register 2026-06-11: HOLD / STAGED', 'Legal hold for real estate funds'],
      nextGate: 'Written legal/compliance signoff from licensed counsel.',
      source: 'declared:control-register-2026-06-11',
      humanApprovalRequired: true,
      verifiedBy: null,
    },
    {
      key: 'truth_inventory_workbook',
      name: '200-Module Truth Inventory Workbook',
      category: 'Strategy',
      bucket: 'reference',
      summary: 'External 200-row AI/module workbook (dashboard, inventory, metrics, truth gates) produced in another session.',
      evidence: ['Workbook exists outside this repository (external sandbox)', 'Reported buckets: 118 staged/locked, 54 planned, 12 demo, 6 legal hold, 5 claimed, 4 reference, 1 blocked'],
      nextGate: 'Commit the workbook (or its CSV export) into the repo so the registry can ingest and measure it.',
      source: 'declared:truth-inventory-xlsx',
      humanApprovalRequired: false,
      verifiedBy: null,
    },
  ],
});

// ---------------------------------------------------------------------------
// Overview composition
// ---------------------------------------------------------------------------

export const getOverview = (): DashboardOverview => ({
  generatedAt: NOW_ISO,
  kpis: getKpis(),
  alerts: getComplianceAlerts().filter((a) => !a.resolved).slice(0, 4),
  agentSummary: getAgentSummary(),
  cash: getCashPosition(),
  pipeline: getPipeline(),
  upcomingMilestones: getJobs()
    .map((j) => ({ jobCode: j.code, milestone: j.nextMilestone, at: j.nextMilestoneAt }))
    .sort((a, b) => Date.parse(a.at) - Date.parse(b.at))
    .slice(0, 5),
});
