import type { PermitSubmission } from './types';

/**
 * Demo submissions used by the dashboard, the API mock, and the test bed.
 * Each one is calibrated to trip a specific cluster of checks so the UI
 * walkthrough shows realistic deficiency reports.
 */
export const FIXTURE_SUBMISSIONS: PermitSubmission[] = [
  {
    id: 'sub-1001',
    permitNumber: 'NBPT-2025-0148',
    jurisdiction: 'newburyport',
    permitType: 'addition',
    occupancy: 'R-3',
    scopeNarrative:
      'Two-story rear addition 18\'×24\' over slab-on-grade with full kitchen renovation.',
    property: {
      addressRaw: '14 High Street, Newburyport MA 01950',
      addressNormalized: '14 HIGH ST, NEWBURYPORT, MA 01950',
      parcelId: '34-12-7',
      lotSqft: 6500,
      inFloodZone: false,
      inHistoricDistrict: true,
      inConservation: false,
    },
    owner: { name: 'Lopez, Maria & James', signedAt: '2025-04-22T10:00:00Z' },
    contractor: {
      name: 'Northshore Builders LLC',
      cslNumber: 'CS-102837',
      hicNumber: '184522',
      licenseExpiresAt: '2026-08-31',
      insurance: {
        carrier: 'Acadia Insurance',
        policy: 'GL-554912',
        expiresAt: '2025-12-15',
      },
    },
    scope: {
      grossSqft: 2400,
      addedSqft: 432,
      storiesAdded: 1,
      valuation: 285_000,
    },
    zoning: {
      district: 'R-2',
      frontSetback: 22,
      rearSetback: 18,
      sideSetback: 8,
      proposedHeight: 28,
      proposedCoveragePct: 32,
      proposedFar: 0.48,
      proposedImperviousPct: 44,
    },
    building: {
      egressWindows: [
        { room: 'Bedroom 1', netClearSqft: 5.9, sillHeightIn: 38 },
        { room: 'Bedroom 2', netClearSqft: 4.8, sillHeightIn: 46 },
      ],
      stairs: [{ riserIn: 7.5, treadIn: 10, widthIn: 36, handrails: 1 }],
      smokeDetectorsPerLevel: 2,
      coDetectors: 1,
      ceilingHeightIn: 96,
      insulationR: { walls: 21, ceiling: 49, floor: 30, basement: 10 },
    },
    files: [
      { name: 'application.pdf', kind: 'application_form', sizeBytes: 220_000, sha256: 'a1', pages: 6, ocrConfidence: 0.94 },
      { name: 'architectural.pdf', kind: 'architectural', sizeBytes: 4_400_000, sha256: 'a2', pages: 8, ocrConfidence: 0.88 },
      { name: 'structural.pdf', kind: 'structural', sizeBytes: 2_100_000, sha256: 'a3', pages: 3, ocrConfidence: 0.9 },
      { name: 'site-plan.pdf', kind: 'site_plan', sizeBytes: 1_300_000, sha256: 'a4', pages: 1, ocrConfidence: 0.93 },
      { name: 'energy-worksheet.pdf', kind: 'energy', sizeBytes: 240_000, sha256: 'a5', pages: 2, ocrConfidence: 0.97 },
      { name: 'coi.pdf', kind: 'insurance_cert', sizeBytes: 120_000, sha256: 'a6', pages: 1, ocrConfidence: 0.99 },
      { name: 'license.pdf', kind: 'license', sizeBytes: 80_000, sha256: 'a7', pages: 1, ocrConfidence: 0.99 },
    ],
    submittedAt: '2025-04-23T14:21:00Z',
  },
  {
    id: 'sub-1002',
    permitNumber: 'AMES-2025-0093',
    jurisdiction: 'amesbury',
    permitType: 'deck',
    occupancy: 'R-3',
    scopeNarrative:
      '14\'×20\' second-story rear deck with hot tub and stairs to grade.',
    property: {
      addressRaw: '88 Pleasant Valley Rd, Amesbury MA 01913',
      addressNormalized: '88 PLEASANT VALLEY RD, AMESBURY, MA 01913',
      parcelId: '101-44',
      lotSqft: 12_500,
      inFloodZone: false,
      inHistoricDistrict: false,
      inConservation: false,
    },
    owner: { name: 'O\'Brien, Patrick', signedAt: '2025-05-01T15:00:00Z' },
    contractor: {
      name: 'Merrimack Decks Inc',
      cslNumber: 'CS-098214',
      hicNumber: '177310',
      licenseExpiresAt: '2025-06-01',
      insurance: {
        carrier: 'Travelers',
        policy: 'GL-7741',
        expiresAt: '2024-11-30',
      },
    },
    scope: {
      deckSqft: 280,
      valuation: 38_000,
    },
    zoning: {
      district: 'R-40',
      frontSetback: 45,
      rearSetback: 22,
      sideSetback: 12,
      proposedHeight: 22,
      proposedCoveragePct: 14,
      proposedFar: 0.18,
      proposedImperviousPct: 22,
    },
    deck: {
      footingDiameterIn: 12,
      footingDepthIn: 36,
      ledgerBoltSpec: '½" lag bolts at 16" o.c.',
      joistSpanFt: 14,
      joistSize: '2x10 SPF',
      guardHeightIn: 34,
      hotTub: true,
      fastenerSpec: 'plain steel deck screws',
    },
    files: [
      { name: 'application.pdf', kind: 'application_form', sizeBytes: 180_000, sha256: 'b1', pages: 4, ocrConfidence: 0.91 },
      { name: 'deck-plans.pdf', kind: 'architectural', sizeBytes: 800_000, sha256: 'b2', pages: 3, ocrConfidence: 0.86 },
      { name: 'site-sketch.pdf', kind: 'site_plan', sizeBytes: 600_000, sha256: 'b3', pages: 1, ocrConfidence: 0.78 },
    ],
    submittedAt: '2025-05-02T09:10:00Z',
  },
  {
    id: 'sub-1003',
    permitNumber: 'SAL-2025-0211',
    jurisdiction: 'salisbury',
    permitType: 'new_construction',
    occupancy: 'R-3',
    scopeNarrative:
      'New single-family residence 2,850 sq ft on previously approved lot. Two-car attached garage.',
    property: {
      addressRaw: '5 Ocean View Way, Salisbury MA 01952',
      addressNormalized: '5 OCEAN VIEW WAY, SALISBURY, MA 01952',
      parcelId: '21-3-8',
      lotSqft: 11_000,
      inFloodZone: true,
      inHistoricDistrict: false,
      inConservation: true,
    },
    owner: { name: 'Coastal Holdings LLC', signedAt: '2025-03-29T12:00:00Z' },
    contractor: {
      name: 'North Atlantic Custom Homes',
      cslNumber: 'CS-115662',
      hicNumber: '193114',
      licenseExpiresAt: '2027-02-28',
      insurance: {
        carrier: 'Liberty Mutual',
        policy: 'GL-883401',
        expiresAt: '2026-03-31',
      },
    },
    scope: {
      grossSqft: 2850,
      valuation: 720_000,
    },
    zoning: {
      district: 'R-A',
      frontSetback: 28,
      rearSetback: 27,
      sideSetback: 16,
      proposedHeight: 33,
      proposedCoveragePct: 28,
      proposedFar: 0.42,
      proposedImperviousPct: 41,
    },
    building: {
      egressWindows: [
        { room: 'Bedroom 1', netClearSqft: 5.9, sillHeightIn: 36 },
        { room: 'Bedroom 2', netClearSqft: 5.8, sillHeightIn: 36 },
        { room: 'Bedroom 3', netClearSqft: 5.9, sillHeightIn: 36 },
      ],
      stairs: [{ riserIn: 7.25, treadIn: 11, widthIn: 36, handrails: 1 }],
      smokeDetectorsPerLevel: 2,
      coDetectors: 2,
      ceilingHeightIn: 108,
      insulationR: { walls: 23, ceiling: 60, floor: 38, basement: 15 },
    },
    files: [
      { name: 'application.pdf', kind: 'application_form', sizeBytes: 240_000, sha256: 'c1', pages: 6, ocrConfidence: 0.96 },
      { name: 'arch-set.pdf', kind: 'architectural', sizeBytes: 8_400_000, sha256: 'c2', pages: 22, ocrConfidence: 0.94 },
      { name: 'structural.pdf', kind: 'structural', sizeBytes: 3_300_000, sha256: 'c3', pages: 7, ocrConfidence: 0.92 },
      { name: 'site-plan.pdf', kind: 'site_plan', sizeBytes: 1_900_000, sha256: 'c4', pages: 2, ocrConfidence: 0.95 },
      { name: 'energy.pdf', kind: 'energy', sizeBytes: 360_000, sha256: 'c5', pages: 4, ocrConfidence: 0.97 },
      { name: 'coi.pdf', kind: 'insurance_cert', sizeBytes: 130_000, sha256: 'c6', pages: 1, ocrConfidence: 0.99 },
      { name: 'license.pdf', kind: 'license', sizeBytes: 90_000, sha256: 'c7', pages: 1, ocrConfidence: 0.99 },
    ],
    submittedAt: '2025-04-01T10:42:00Z',
  },
];
